// ARENA FANTASY - Players Database
// Brasileirão Série A 2026 - Elencos completos
const PLAYERS_DATABASE = [
  {id:1,name:"Rossi",club:"FLA",position:"GOL",cost:0,projPoints:93.8,realPoints:0,jogos:18,gols:0,assistencias:0,cleanSheets:5,status:"disponivel",draftedBy:null},
  {id:2,name:"Andrew",club:"FLA",position:"GOL",cost:0,projPoints:26.1,realPoints:0,jogos:2,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:3,name:"Dyogo Alves",club:"FLA",position:"GOL",cost:0,projPoints:0,realPoints:0,jogos:0,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:4,name:"Guillermo Varela",club:"FLA",position:"LAT",cost:0,projPoints:68.8,realPoints:0,jogos:15,gols:0,assistencias:2,cleanSheets:5,status:"disponivel",draftedBy:null},
  {id:5,name:"Emerson Royal",club:"FLA",position:"LAT",cost:0,projPoints:84.9,realPoints:0,jogos:16,gols:0,assistencias:3,cleanSheets:5,status:"disponivel",draftedBy:null},
  {id:6,name:"Ayrton Lucas",club:"FLA",position:"LAT",cost:0,projPoints:87.5,realPoints:0,jogos:15,gols:1,assistencias:2,cleanSheets:5,status:"disponivel",draftedBy:null},
  {id:7,name:"Alex Sandro",club:"FLA",position:"LAT",cost:0,projPoints:63.9,realPoints:0,jogos:8,gols:0,assistencias:1,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:8,name:"Léo Pereira",club:"FLA",position:"ZAG",cost:0,projPoints:89.3,realPoints:0,jogos:17,gols:1,assistencias:1,cleanSheets:5,status:"disponivel",draftedBy:null},
  {id:9,name:"Léo Ortiz",club:"FLA",position:"ZAG",cost:0,projPoints:82.5,realPoints:0,jogos:16,gols:0,assistencias:2,cleanSheets:5,status:"disponivel",draftedBy:null},
  {id:10,name:"Vitão",club:"FLA",position:"ZAG",cost:0,projPoints:61.7,realPoints:0,jogos:10,gols:0,assistencias:0,cleanSheets:3,status:"disponivel",draftedBy:null},
  {id:11,name:"João Victor",club:"FLA",position:"ZAG",cost:0,projPoints:56.1,realPoints:0,jogos:12,gols:0,assistencias:0,cleanSheets:3,status:"disponivel",draftedBy:null},
  {id:12,name:"Danilo",club:"FLA",position:"ZAG",cost:0,projPoints:57.2,realPoints:0,jogos:8,gols:0,assistencias:0,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:13,name:"Arrascaeta",club:"FLA",position:"MEI",cost:0,projPoints:117.5,realPoints:0,jogos:16,gols:4,assistencias:5,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:14,name:"De la Cruz",club:"FLA",position:"MEI",cost:0,projPoints:93.1,realPoints:0,jogos:15,gols:2,assistencias:3,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:15,name:"Lucas Paquetá",club:"FLA",position:"MEI",cost:0,projPoints:92.3,realPoints:0,jogos:14,gols:2,assistencias:3,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:16,name:"Gerson",club:"FLA",position:"MEI",cost:0,projPoints:115.8,realPoints:0,jogos:17,gols:2,assistencias:4,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:17,name:"Andreas Pereira",club:"FLA",position:"MEI",cost:0,projPoints:126.0,realPoints:0,jogos:18,gols:3,assistencias:8,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:18,name:"Jorginho",club:"FLA",position:"MEI",cost:0,projPoints:89.6,realPoints:0,jogos:12,gols:0,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:19,name:"Pulgar",club:"FLA",position:"MEI",cost:0,projPoints:78.1,realPoints:0,jogos:10,gols:0,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:20,name:"Saúl Ñíguez",club:"FLA",position:"MEI",cost:0,projPoints:61.3,realPoints:0,jogos:8,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:21,name:"Evertton Araújo",club:"FLA",position:"MEI",cost:0,projPoints:52.7,realPoints:0,jogos:5,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:22,name:"Pedro",club:"FLA",position:"ATA",cost:0,projPoints:133.2,realPoints:0,jogos:17,gols:10,assistencias:3,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:23,name:"Bruno Henrique",club:"FLA",position:"ATA",cost:0,projPoints:68.9,realPoints:0,jogos:12,gols:3,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:24,name:"Everton Cebolinha",club:"FLA",position:"ATA",cost:0,projPoints:71.9,realPoints:0,jogos:10,gols:2,assistencias:2,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:25,name:"Luiz Araújo",club:"FLA",position:"ATA",cost:0,projPoints:63.4,realPoints:0,jogos:12,gols:2,assistencias:2,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:26,name:"Samuel Lino",club:"FLA",position:"ATA",cost:0,projPoints:57.0,realPoints:0,jogos:11,gols:2,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:27,name:"Gonzalo Plata",club:"FLA",position:"ATA",cost:0,projPoints:46.9,realPoints:0,jogos:9,gols:1,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:28,name:"Wallace Yan",club:"FLA",position:"ATA",cost:0,projPoints:40.0,realPoints:0,jogos:6,gols:1,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:30,name:"Carlos Miguel",club:"PAL",position:"GOL",cost:0,projPoints:142.3,realPoints:0,jogos:18,gols:0,assistencias:0,cleanSheets:8,status:"disponivel",draftedBy:null},
  {id:31,name:"Marcelo Lomba",club:"PAL",position:"GOL",cost:0,projPoints:36.1,realPoints:0,jogos:1,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:32,name:"Aranha",club:"PAL",position:"GOL",cost:0,projPoints:0,realPoints:0,jogos:0,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:33,name:"Gustavo Gómez",club:"PAL",position:"ZAG",cost:0,projPoints:99.6,realPoints:0,jogos:18,gols:1,assistencias:0,cleanSheets:8,status:"disponivel",draftedBy:null},
  {id:34,name:"Murilo",club:"PAL",position:"ZAG",cost:0,projPoints:93.0,realPoints:0,jogos:17,gols:0,assistencias:1,cleanSheets:8,status:"disponivel",draftedBy:null},
  {id:35,name:"Bruno Fuchs",club:"PAL",position:"ZAG",cost:0,projPoints:76.4,realPoints:0,jogos:15,gols:0,assistencias:0,cleanSheets:6,status:"disponivel",draftedBy:null},
  {id:36,name:"Benedetti",club:"PAL",position:"ZAG",cost:0,projPoints:63.7,realPoints:0,jogos:6,gols:0,assistencias:0,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:37,name:"Piquerez",club:"PAL",position:"LAT",cost:0,projPoints:99.3,realPoints:0,jogos:17,gols:1,assistencias:3,cleanSheets:8,status:"disponivel",draftedBy:null},
  {id:38,name:"Jefté",club:"PAL",position:"LAT",cost:0,projPoints:65.3,realPoints:0,jogos:14,gols:0,assistencias:1,cleanSheets:5,status:"disponivel",draftedBy:null},
  {id:39,name:"Agustín Giay",club:"PAL",position:"LAT",cost:0,projPoints:67.2,realPoints:0,jogos:12,gols:0,assistencias:1,cleanSheets:4,status:"disponivel",draftedBy:null},
  {id:40,name:"Khellven",club:"PAL",position:"LAT",cost:0,projPoints:56.8,realPoints:0,jogos:5,gols:0,assistencias:0,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:41,name:"Marlon Freitas",club:"PAL",position:"MEI",cost:0,projPoints:107.8,realPoints:0,jogos:17,gols:1,assistencias:2,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:42,name:"Andreas Pereira PAL",club:"PAL",position:"MEI",cost:0,projPoints:108.3,realPoints:0,jogos:14,gols:2,assistencias:4,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:43,name:"Raphael Veiga",club:"PAL",position:"MEI",cost:0,projPoints:111.5,realPoints:0,jogos:17,gols:3,assistencias:6,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:44,name:"Jhon Arias",club:"PAL",position:"MEI",cost:0,projPoints:98.2,realPoints:0,jogos:14,gols:2,assistencias:3,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:45,name:"Mauricio",club:"PAL",position:"MEI",cost:0,projPoints:80.3,realPoints:0,jogos:13,gols:1,assistencias:2,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:46,name:"Gabriel Menino",club:"PAL",position:"MEI",cost:0,projPoints:94.4,realPoints:0,jogos:15,gols:1,assistencias:4,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:47,name:"Allan",club:"PAL",position:"MEI",cost:0,projPoints:62.6,realPoints:0,jogos:9,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:48,name:"Emiliano Martínez",club:"PAL",position:"MEI",cost:0,projPoints:56.8,realPoints:0,jogos:7,gols:0,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:49,name:"Larson",club:"PAL",position:"MEI",cost:0,projPoints:44.1,realPoints:0,jogos:6,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:50,name:"Felipe Anderson",club:"PAL",position:"MEI",cost:0,projPoints:69.9,realPoints:0,jogos:10,gols:1,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:51,name:"Vitor Roque",club:"PAL",position:"ATA",cost:0,projPoints:91.1,realPoints:0,jogos:16,gols:6,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:52,name:"Estêvão",club:"PAL",position:"ATA",cost:0,projPoints:103.2,realPoints:0,jogos:17,gols:7,assistencias:2,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:53,name:"Flaco López",club:"PAL",position:"ATA",cost:0,projPoints:69.9,realPoints:0,jogos:12,gols:3,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:54,name:"Ramón Sosa",club:"PAL",position:"ATA",cost:0,projPoints:60.7,realPoints:0,jogos:11,gols:2,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:55,name:"Paulinho",club:"PAL",position:"ATA",cost:0,projPoints:39.4,realPoints:0,jogos:8,gols:1,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:56,name:"Luighi",club:"PAL",position:"ATA",cost:0,projPoints:46.8,realPoints:0,jogos:6,gols:1,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:57,name:"Bruno Rodrigues",club:"PAL",position:"ATA",cost:0,projPoints:19.2,realPoints:0,jogos:4,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:60,name:"John",club:"BOT",position:"GOL",cost:0,projPoints:71.0,realPoints:0,jogos:17,gols:0,assistencias:0,cleanSheets:3,status:"disponivel",draftedBy:null},
  {id:61,name:"Gabriel Brazão",club:"BOT",position:"GOL",cost:0,projPoints:26.1,realPoints:0,jogos:2,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:62,name:"Alexander Barboza",club:"BOT",position:"ZAG",cost:0,projPoints:62.8,realPoints:0,jogos:17,gols:1,assistencias:0,cleanSheets:3,status:"disponivel",draftedBy:null},
  {id:63,name:"Riquelme",club:"BOT",position:"ZAG",cost:0,projPoints:49.3,realPoints:0,jogos:12,gols:0,assistencias:0,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:64,name:"Ythallo",club:"BOT",position:"ZAG",cost:0,projPoints:40.9,realPoints:0,jogos:8,gols:0,assistencias:0,cleanSheets:1,status:"disponivel",draftedBy:null},
  {id:65,name:"Vitinho",club:"BOT",position:"LAT",cost:0,projPoints:58.3,realPoints:0,jogos:15,gols:0,assistencias:1,cleanSheets:3,status:"disponivel",draftedBy:null},
  {id:66,name:"Jhoan Hernández",club:"BOT",position:"LAT",cost:0,projPoints:51.7,realPoints:0,jogos:12,gols:0,assistencias:1,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:67,name:"Marçal",club:"BOT",position:"LAT",cost:0,projPoints:42.1,realPoints:0,jogos:9,gols:0,assistencias:0,cleanSheets:1,status:"disponivel",draftedBy:null},
  {id:68,name:"Danilo BOT",club:"BOT",position:"MEI",cost:0,projPoints:125.7,realPoints:0,jogos:17,gols:7,assistencias:2,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:69,name:"Cristian Medina",club:"BOT",position:"MEI",cost:0,projPoints:72.7,realPoints:0,jogos:14,gols:1,assistencias:2,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:70,name:"Álvaro Montoro",club:"BOT",position:"MEI",cost:0,projPoints:52.7,realPoints:0,jogos:12,gols:0,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:71,name:"Wallace Davi",club:"BOT",position:"MEI",cost:0,projPoints:47.8,realPoints:0,jogos:9,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:72,name:"Nathan Fernandes",club:"BOT",position:"MEI",cost:0,projPoints:42.5,realPoints:0,jogos:7,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:73,name:"Savarino",club:"BOT",position:"ATA",cost:0,projPoints:82.6,realPoints:0,jogos:15,gols:4,assistencias:3,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:74,name:"Arthur Cabral",club:"BOT",position:"ATA",cost:0,projPoints:91.1,realPoints:0,jogos:16,gols:7,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:75,name:"Luiz Henrique",club:"BOT",position:"ATA",cost:0,projPoints:80.6,realPoints:0,jogos:15,gols:4,assistencias:3,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:76,name:"Lucas Villalba",club:"BOT",position:"ATA",cost:0,projPoints:40.3,realPoints:0,jogos:9,gols:1,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:77,name:"Artur",club:"BOT",position:"ATA",cost:0,projPoints:32.3,realPoints:0,jogos:7,gols:1,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:80,name:"Cássio",club:"CRU",position:"GOL",cost:0,projPoints:68.0,realPoints:0,jogos:17,gols:0,assistencias:0,cleanSheets:3,status:"disponivel",draftedBy:null},
  {id:81,name:"Anderson",club:"CRU",position:"GOL",cost:0,projPoints:16.1,realPoints:0,jogos:2,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:82,name:"Fabrício Bruno",club:"CRU",position:"ZAG",cost:0,projPoints:67.9,realPoints:0,jogos:17,gols:0,assistencias:1,cleanSheets:3,status:"disponivel",draftedBy:null},
  {id:83,name:"Jonathan Jesus",club:"CRU",position:"ZAG",cost:0,projPoints:53.4,realPoints:0,jogos:14,gols:0,assistencias:0,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:84,name:"Zé Ivaldo",club:"CRU",position:"ZAG",cost:0,projPoints:47.3,realPoints:0,jogos:10,gols:0,assistencias:0,cleanSheets:1,status:"disponivel",draftedBy:null},
  {id:85,name:"William",club:"CRU",position:"LAT",cost:0,projPoints:60.8,realPoints:0,jogos:16,gols:0,assistencias:2,cleanSheets:3,status:"disponivel",draftedBy:null},
  {id:86,name:"Kaiki",club:"CRU",position:"LAT",cost:0,projPoints:49.3,realPoints:0,jogos:10,gols:0,assistencias:1,cleanSheets:1,status:"disponivel",draftedBy:null},
  {id:87,name:"Marlon",club:"CRU",position:"LAT",cost:0,projPoints:36.8,realPoints:0,jogos:8,gols:0,assistencias:0,cleanSheets:1,status:"disponivel",draftedBy:null},
  {id:88,name:"Lucas Silva",club:"CRU",position:"MEI",cost:0,projPoints:72.9,realPoints:0,jogos:15,gols:0,assistencias:2,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:89,name:"Lucas Romero",club:"CRU",position:"MEI",cost:0,projPoints:71.6,realPoints:0,jogos:12,gols:0,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:90,name:"Gerson CRU",club:"CRU",position:"MEI",cost:0,projPoints:103.9,realPoints:0,jogos:14,gols:2,assistencias:3,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:91,name:"Matheus Pereira",club:"CRU",position:"MEI",cost:0,projPoints:86.2,realPoints:0,jogos:17,gols:2,assistencias:3,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:92,name:"Kaio Jorge",club:"CRU",position:"ATA",cost:0,projPoints:74.0,realPoints:0,jogos:17,gols:5,assistencias:2,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:93,name:"Wanderson",club:"CRU",position:"ATA",cost:0,projPoints:51.3,realPoints:0,jogos:12,gols:2,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:94,name:"Arroyo",club:"CRU",position:"ATA",cost:0,projPoints:41.1,realPoints:0,jogos:10,gols:1,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:95,name:"Gabriel Veron",club:"CRU",position:"ATA",cost:0,projPoints:35.2,realPoints:0,jogos:7,gols:1,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:100,name:"Marcos Felipe",club:"BAH",position:"GOL",cost:0,projPoints:68.0,realPoints:0,jogos:17,gols:0,assistencias:0,cleanSheets:3,status:"disponivel",draftedBy:null},
  {id:101,name:"João Paulo BAH",club:"BAH",position:"GOL",cost:0,projPoints:26.1,realPoints:0,jogos:2,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:102,name:"Gabriel Xavier",club:"BAH",position:"ZAG",cost:0,projPoints:75.6,realPoints:0,jogos:17,gols:1,assistencias:1,cleanSheets:3,status:"disponivel",draftedBy:null},
  {id:103,name:"Kanu",club:"BAH",position:"ZAG",cost:0,projPoints:52.8,realPoints:0,jogos:15,gols:0,assistencias:0,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:104,name:"Luiz Gustavo",club:"BAH",position:"ZAG",cost:0,projPoints:47.0,realPoints:0,jogos:8,gols:0,assistencias:0,cleanSheets:1,status:"disponivel",draftedBy:null},
  {id:105,name:"Luciano Juba",club:"BAH",position:"LAT",cost:0,projPoints:118.8,realPoints:0,jogos:17,gols:7,assistencias:2,cleanSheets:3,status:"disponivel",draftedBy:null},
  {id:106,name:"Santiago Arias",club:"BAH",position:"LAT",cost:0,projPoints:51.7,realPoints:0,jogos:12,gols:0,assistencias:1,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:107,name:"Acevedo",club:"BAH",position:"MEI",cost:0,projPoints:62.3,realPoints:0,jogos:14,gols:0,assistencias:2,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:108,name:"Everton Ribeiro",club:"BAH",position:"MEI",cost:0,projPoints:69.4,realPoints:0,jogos:15,gols:1,assistencias:2,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:109,name:"Michel Araújo",club:"BAH",position:"MEI",cost:0,projPoints:50.1,realPoints:0,jogos:13,gols:0,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:110,name:"Cauly",club:"BAH",position:"MEI",cost:0,projPoints:65.3,realPoints:0,jogos:14,gols:1,assistencias:2,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:111,name:"Vitinho BAH",club:"BAH",position:"MEI",cost:0,projPoints:47.3,realPoints:0,jogos:10,gols:0,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:112,name:"Willian José",club:"BAH",position:"ATA",cost:0,projPoints:67.1,realPoints:0,jogos:14,gols:4,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:113,name:"Iago",club:"BAH",position:"ATA",cost:0,projPoints:65.1,realPoints:0,jogos:12,gols:3,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:114,name:"Kayky",club:"BAH",position:"ATA",cost:0,projPoints:31.7,realPoints:0,jogos:8,gols:1,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:120,name:"Rafael",club:"SPFC",position:"GOL",cost:0,projPoints:76.9,realPoints:0,jogos:17,gols:0,assistencias:0,cleanSheets:4,status:"disponivel",draftedBy:null},
  {id:121,name:"Young",club:"SPFC",position:"GOL",cost:0,projPoints:16.1,realPoints:0,jogos:2,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:122,name:"Arboleda",club:"SPFC",position:"ZAG",cost:0,projPoints:58.8,realPoints:0,jogos:16,gols:0,assistencias:0,cleanSheets:4,status:"disponivel",draftedBy:null},
  {id:123,name:"Alan Franco",club:"SPFC",position:"ZAG",cost:0,projPoints:53.7,realPoints:0,jogos:14,gols:0,assistencias:0,cleanSheets:3,status:"disponivel",draftedBy:null},
  {id:124,name:"Sabino",club:"SPFC",position:"ZAG",cost:0,projPoints:52.8,realPoints:0,jogos:9,gols:0,assistencias:0,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:125,name:"Diaz",club:"SPFC",position:"ZAG",cost:0,projPoints:44.1,realPoints:0,jogos:6,gols:0,assistencias:0,cleanSheets:1,status:"disponivel",draftedBy:null},
  {id:126,name:"Welington",club:"SPFC",position:"LAT",cost:0,projPoints:66.7,realPoints:0,jogos:15,gols:0,assistencias:2,cleanSheets:4,status:"disponivel",draftedBy:null},
  {id:127,name:"Maik",club:"SPFC",position:"LAT",cost:0,projPoints:56.0,realPoints:0,jogos:9,gols:0,assistencias:1,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:128,name:"Igor Vinícius",club:"SPFC",position:"LAT",cost:0,projPoints:38.2,realPoints:0,jogos:7,gols:0,assistencias:0,cleanSheets:1,status:"disponivel",draftedBy:null},
  {id:129,name:"Marcos Antonio",club:"SPFC",position:"MEI",cost:0,projPoints:56.4,realPoints:0,jogos:14,gols:0,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:130,name:"Luciano SPFC",club:"SPFC",position:"MEI",cost:0,projPoints:89.8,realPoints:0,jogos:16,gols:3,assistencias:2,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:131,name:"Danielzinho",club:"SPFC",position:"MEI",cost:0,projPoints:53.2,realPoints:0,jogos:13,gols:0,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:132,name:"Bobadilla",club:"SPFC",position:"MEI",cost:0,projPoints:47.3,realPoints:0,jogos:10,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:133,name:"Cauly SPFC",club:"SPFC",position:"MEI",cost:0,projPoints:67.7,realPoints:0,jogos:13,gols:1,assistencias:2,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:134,name:"Oscar",club:"SPFC",position:"MEI",cost:0,projPoints:47.8,realPoints:0,jogos:11,gols:0,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:135,name:"Calleri",club:"SPFC",position:"ATA",cost:0,projPoints:62.4,realPoints:0,jogos:16,gols:4,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:136,name:"André Silva",club:"SPFC",position:"ATA",cost:0,projPoints:43.7,realPoints:0,jogos:11,gols:2,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:140,name:"Everson",club:"CAM",position:"GOL",cost:0,projPoints:68.0,realPoints:0,jogos:17,gols:0,assistencias:0,cleanSheets:3,status:"disponivel",draftedBy:null},
  {id:141,name:"Matheus Mendes",club:"CAM",position:"GOL",cost:0,projPoints:16.1,realPoints:0,jogos:2,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:142,name:"Ruan",club:"CAM",position:"ZAG",cost:0,projPoints:53.5,realPoints:0,jogos:16,gols:0,assistencias:0,cleanSheets:3,status:"disponivel",draftedBy:null},
  {id:143,name:"Vitor Hugo",club:"CAM",position:"ZAG",cost:0,projPoints:47.8,realPoints:0,jogos:14,gols:0,assistencias:0,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:144,name:"Guilherme Arana",club:"CAM",position:"LAT",cost:0,projPoints:61.6,realPoints:0,jogos:16,gols:0,assistencias:2,cleanSheets:3,status:"disponivel",draftedBy:null},
  {id:145,name:"Renan Lodi",club:"CAM",position:"LAT",cost:0,projPoints:54.9,realPoints:0,jogos:14,gols:0,assistencias:2,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:146,name:"Preciado",club:"CAM",position:"LAT",cost:0,projPoints:35.8,realPoints:0,jogos:9,gols:0,assistencias:0,cleanSheets:1,status:"disponivel",draftedBy:null},
  {id:147,name:"Alisson",club:"CAM",position:"MEI",cost:0,projPoints:53.4,realPoints:0,jogos:14,gols:0,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:148,name:"Maycon",club:"CAM",position:"MEI",cost:0,projPoints:53.4,realPoints:0,jogos:12,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:149,name:"Bernard",club:"CAM",position:"MEI",cost:0,projPoints:67.4,realPoints:0,jogos:15,gols:2,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:150,name:"Cuello",club:"CAM",position:"MEI",cost:0,projPoints:70.5,realPoints:0,jogos:16,gols:2,assistencias:2,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:151,name:"Victor Hugo CAM",club:"CAM",position:"ATA",cost:0,projPoints:82.5,realPoints:0,jogos:14,gols:5,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:152,name:"Bruninho",club:"CAM",position:"ATA",cost:0,projPoints:28.9,realPoints:0,jogos:9,gols:1,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:153,name:"Alan Kardec",club:"CAM",position:"ATA",cost:0,projPoints:32.3,realPoints:0,jogos:7,gols:1,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:160,name:"Hugo Souza",club:"COR",position:"GOL",cost:0,projPoints:47.3,realPoints:0,jogos:16,gols:0,assistencias:0,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:161,name:"Matheus Donelli",club:"COR",position:"GOL",cost:0,projPoints:22.9,realPoints:0,jogos:3,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:162,name:"Félix Torres",club:"COR",position:"ZAG",cost:0,projPoints:51.4,realPoints:0,jogos:15,gols:0,assistencias:0,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:163,name:"André Ramalho",club:"COR",position:"ZAG",cost:0,projPoints:46.9,realPoints:0,jogos:13,gols:0,assistencias:0,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:164,name:"Gustavo Henrique",club:"COR",position:"ZAG",cost:0,projPoints:40.9,realPoints:0,jogos:8,gols:0,assistencias:0,cleanSheets:1,status:"disponivel",draftedBy:null},
  {id:165,name:"Matheuzinho",club:"COR",position:"LAT",cost:0,projPoints:54.2,realPoints:0,jogos:15,gols:0,assistencias:1,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:166,name:"Matheus Bidu",club:"COR",position:"LAT",cost:0,projPoints:51.1,realPoints:0,jogos:14,gols:0,assistencias:1,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:167,name:"Rodrigo Garro",club:"COR",position:"MEI",cost:0,projPoints:88.8,realPoints:0,jogos:16,gols:3,assistencias:2,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:168,name:"Charles",club:"COR",position:"MEI",cost:0,projPoints:63.8,realPoints:0,jogos:14,gols:0,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:169,name:"Raniele",club:"COR",position:"MEI",cost:0,projPoints:55.0,realPoints:0,jogos:13,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:170,name:"Bidon",club:"COR",position:"MEI",cost:0,projPoints:45.2,realPoints:0,jogos:10,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:171,name:"Carrillo",club:"COR",position:"MEI",cost:0,projPoints:33.2,realPoints:0,jogos:8,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:172,name:"Memphis Depay",club:"COR",position:"ATA",cost:0,projPoints:61.1,realPoints:0,jogos:14,gols:3,assistencias:2,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:173,name:"Yuri Alberto",club:"COR",position:"ATA",cost:0,projPoints:76.2,realPoints:0,jogos:16,gols:5,assistencias:2,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:174,name:"Talles Magno",club:"COR",position:"ATA",cost:0,projPoints:28.9,realPoints:0,jogos:9,gols:1,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:180,name:"Weverton",club:"GRE",position:"GOL",cost:0,projPoints:82.3,realPoints:0,jogos:17,gols:0,assistencias:0,cleanSheets:4,status:"disponivel",draftedBy:null},
  {id:181,name:"Grando",club:"GRE",position:"GOL",cost:0,projPoints:26.1,realPoints:0,jogos:2,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:182,name:"Gustavo Martins",club:"GRE",position:"ZAG",cost:0,projPoints:56.9,realPoints:0,jogos:15,gols:0,assistencias:0,cleanSheets:3,status:"disponivel",draftedBy:null},
  {id:183,name:"Wagner Leonardo",club:"GRE",position:"ZAG",cost:0,projPoints:52.2,realPoints:0,jogos:14,gols:0,assistencias:0,cleanSheets:3,status:"disponivel",draftedBy:null},
  {id:184,name:"Kannemann",club:"GRE",position:"ZAG",cost:0,projPoints:53.4,realPoints:0,jogos:10,gols:0,assistencias:0,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:185,name:"Caio Paulista",club:"GRE",position:"LAT",cost:0,projPoints:53.5,realPoints:0,jogos:15,gols:0,assistencias:1,cleanSheets:3,status:"disponivel",draftedBy:null},
  {id:186,name:"Marcos Rocha",club:"GRE",position:"LAT",cost:0,projPoints:53.4,realPoints:0,jogos:14,gols:0,assistencias:1,cleanSheets:3,status:"disponivel",draftedBy:null},
  {id:187,name:"Reinaldo",club:"GRE",position:"LAT",cost:0,projPoints:38.0,realPoints:0,jogos:9,gols:0,assistencias:0,cleanSheets:1,status:"disponivel",draftedBy:null},
  {id:188,name:"Edenilson",club:"GRE",position:"MEI",cost:0,projPoints:66.8,realPoints:0,jogos:14,gols:0,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:189,name:"Cristaldo",club:"GRE",position:"MEI",cost:0,projPoints:85.9,realPoints:0,jogos:16,gols:2,assistencias:3,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:190,name:"Monsalve",club:"GRE",position:"MEI",cost:0,projPoints:64.0,realPoints:0,jogos:16,gols:1,assistencias:2,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:191,name:"Dodi",club:"GRE",position:"MEI",cost:0,projPoints:46.8,realPoints:0,jogos:11,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:192,name:"Carlos Vinícius",club:"GRE",position:"ATA",cost:0,projPoints:108.5,realPoints:0,jogos:17,gols:9,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:193,name:"Tetê",club:"GRE",position:"ATA",cost:0,projPoints:57.7,realPoints:0,jogos:13,gols:2,assistencias:2,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:194,name:"Amuzu",club:"GRE",position:"ATA",cost:0,projPoints:46.2,realPoints:0,jogos:12,gols:1,assistencias:2,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:195,name:"Aravena",club:"GRE",position:"ATA",cost:0,projPoints:40.1,realPoints:0,jogos:11,gols:1,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:200,name:"Fábio",club:"FLU",position:"GOL",cost:0,projPoints:121.5,realPoints:0,jogos:17,gols:0,assistencias:0,cleanSheets:7,status:"disponivel",draftedBy:null},
  {id:201,name:"Vitor Eudes",club:"FLU",position:"GOL",cost:0,projPoints:26.1,realPoints:0,jogos:2,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:202,name:"Freytes",club:"FLU",position:"ZAG",cost:0,projPoints:61.1,realPoints:0,jogos:14,gols:0,assistencias:0,cleanSheets:4,status:"disponivel",draftedBy:null},
  {id:203,name:"Jemmes",club:"FLU",position:"ZAG",cost:0,projPoints:61.2,realPoints:0,jogos:13,gols:0,assistencias:0,cleanSheets:4,status:"disponivel",draftedBy:null},
  {id:204,name:"Ignácio",club:"FLU",position:"ZAG",cost:0,projPoints:57.7,realPoints:0,jogos:11,gols:0,assistencias:0,cleanSheets:3,status:"disponivel",draftedBy:null},
  {id:205,name:"Samuel Xavier",club:"FLU",position:"LAT",cost:0,projPoints:64.6,realPoints:0,jogos:15,gols:0,assistencias:1,cleanSheets:5,status:"disponivel",draftedBy:null},
  {id:206,name:"Diogo Barbosa",club:"FLU",position:"LAT",cost:0,projPoints:63.0,realPoints:0,jogos:13,gols:0,assistencias:1,cleanSheets:4,status:"disponivel",draftedBy:null},
  {id:207,name:"Renê",club:"FLU",position:"LAT",cost:0,projPoints:47.0,realPoints:0,jogos:8,gols:0,assistencias:0,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:208,name:"Martinelli",club:"FLU",position:"MEI",cost:0,projPoints:56.9,realPoints:0,jogos:15,gols:0,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:209,name:"Hércules",club:"FLU",position:"MEI",cost:0,projPoints:51.0,realPoints:0,jogos:13,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:210,name:"Ganso",club:"FLU",position:"MEI",cost:0,projPoints:62.5,realPoints:0,jogos:15,gols:1,assistencias:2,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:211,name:"Lima",club:"FLU",position:"MEI",cost:0,projPoints:51.4,realPoints:0,jogos:10,gols:0,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:212,name:"Bernal",club:"FLU",position:"MEI",cost:0,projPoints:55.8,realPoints:0,jogos:9,gols:0,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:213,name:"John Kennedy",club:"FLU",position:"ATA",cost:0,projPoints:102.4,realPoints:0,jogos:17,gols:8,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:214,name:"Hulk",club:"FLU",position:"ATA",cost:0,projPoints:83.4,realPoints:0,jogos:14,gols:5,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:215,name:"Canobbio",club:"FLU",position:"ATA",cost:0,projPoints:60.9,realPoints:0,jogos:13,gols:2,assistencias:2,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:216,name:"Rony",club:"FLU",position:"ATA",cost:0,projPoints:52.7,realPoints:0,jogos:12,gols:2,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:217,name:"Germán Cano",club:"FLU",position:"ATA",cost:0,projPoints:49.3,realPoints:0,jogos:10,gols:2,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:218,name:"Everaldo",club:"FLU",position:"ATA",cost:0,projPoints:36.8,realPoints:0,jogos:8,gols:1,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:220,name:"Léo Jardim",club:"VAS",position:"GOL",cost:0,projPoints:47.3,realPoints:0,jogos:16,gols:0,assistencias:0,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:221,name:"Keiller",club:"VAS",position:"GOL",cost:0,projPoints:12.8,realPoints:0,jogos:3,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:222,name:"João Victor VAS",club:"VAS",position:"ZAG",cost:0,projPoints:47.2,realPoints:0,jogos:15,gols:0,assistencias:0,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:223,name:"Maicon",club:"VAS",position:"ZAG",cost:0,projPoints:46.9,realPoints:0,jogos:13,gols:0,assistencias:0,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:224,name:"Paulo Henrique",club:"VAS",position:"ZAG",cost:0,projPoints:39.9,realPoints:0,jogos:9,gols:0,assistencias:0,cleanSheets:1,status:"disponivel",draftedBy:null},
  {id:225,name:"Cuesta",club:"VAS",position:"ZAG",cost:0,projPoints:39.3,realPoints:0,jogos:7,gols:0,assistencias:0,cleanSheets:1,status:"disponivel",draftedBy:null},
  {id:226,name:"Lucas Piton",club:"VAS",position:"LAT",cost:0,projPoints:61.0,realPoints:0,jogos:17,gols:1,assistencias:2,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:227,name:"Puma Rodríguez",club:"VAS",position:"LAT",cost:0,projPoints:47.5,realPoints:0,jogos:14,gols:0,assistencias:1,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:228,name:"Victor Luis",club:"VAS",position:"LAT",cost:0,projPoints:36.8,realPoints:0,jogos:8,gols:0,assistencias:0,cleanSheets:1,status:"disponivel",draftedBy:null},
  {id:229,name:"Guga",club:"VAS",position:"LAT",cost:0,projPoints:34.6,realPoints:0,jogos:6,gols:0,assistencias:0,cleanSheets:1,status:"disponivel",draftedBy:null},
  {id:230,name:"Hugo Moura",club:"VAS",position:"MEI",cost:0,projPoints:52.6,realPoints:0,jogos:13,gols:0,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:231,name:"Mateus Cocão",club:"VAS",position:"MEI",cost:0,projPoints:41.1,realPoints:0,jogos:10,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:232,name:"Payet",club:"VAS",position:"MEI",cost:0,projPoints:70.1,realPoints:0,jogos:14,gols:2,assistencias:2,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:233,name:"Rayan",club:"VAS",position:"ATA",cost:0,projPoints:68.4,realPoints:0,jogos:16,gols:4,assistencias:2,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:234,name:"Brenner",club:"VAS",position:"ATA",cost:0,projPoints:53.7,realPoints:0,jogos:14,gols:3,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:235,name:"Vegetti",club:"VAS",position:"ATA",cost:0,projPoints:41.1,realPoints:0,jogos:10,gols:2,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:240,name:"Rochet",club:"INT",position:"GOL",cost:0,projPoints:69.2,realPoints:0,jogos:17,gols:0,assistencias:0,cleanSheets:3,status:"disponivel",draftedBy:null},
  {id:241,name:"Kauan Canned",club:"INT",position:"GOL",cost:0,projPoints:16.1,realPoints:0,jogos:2,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:242,name:"Vitão INT",club:"INT",position:"ZAG",cost:0,projPoints:53.4,realPoints:0,jogos:14,gols:0,assistencias:0,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:243,name:"Mercado",club:"INT",position:"ZAG",cost:0,projPoints:49.3,realPoints:0,jogos:12,gols:0,assistencias:0,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:244,name:"Clayton Sampaio",club:"INT",position:"ZAG",cost:0,projPoints:40.9,realPoints:0,jogos:8,gols:0,assistencias:0,cleanSheets:1,status:"disponivel",draftedBy:null},
  {id:245,name:"Bernabei",club:"INT",position:"LAT",cost:0,projPoints:52.0,realPoints:0,jogos:17,gols:0,assistencias:1,cleanSheets:3,status:"disponivel",draftedBy:null},
  {id:246,name:"Bruno Gomes",club:"INT",position:"LAT",cost:0,projPoints:39.1,realPoints:0,jogos:10,gols:0,assistencias:0,cleanSheets:1,status:"disponivel",draftedBy:null},
  {id:247,name:"Thiago Maia",club:"INT",position:"MEI",cost:0,projPoints:78.6,realPoints:0,jogos:16,gols:0,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:248,name:"Alan Patrick",club:"INT",position:"MEI",cost:0,projPoints:92.4,realPoints:0,jogos:17,gols:2,assistencias:4,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:249,name:"Rodrigo Villagra",club:"INT",position:"MEI",cost:0,projPoints:54.2,realPoints:0,jogos:13,gols:0,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:250,name:"Bruno Henrique INT",club:"INT",position:"MEI",cost:0,projPoints:45.0,realPoints:0,jogos:11,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:251,name:"Borré",club:"INT",position:"ATA",cost:0,projPoints:57.2,realPoints:0,jogos:16,gols:3,assistencias:2,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:252,name:"Wesley",club:"INT",position:"ATA",cost:0,projPoints:66.7,realPoints:0,jogos:15,gols:4,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:253,name:"Vitinho INT",club:"INT",position:"ATA",cost:0,projPoints:51.3,realPoints:0,jogos:12,gols:2,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:254,name:"Carbonero",club:"INT",position:"ATA",cost:0,projPoints:55.1,realPoints:0,jogos:11,gols:2,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:260,name:"Cleiton",club:"BRA",position:"GOL",cost:0,projPoints:63.8,realPoints:0,jogos:17,gols:0,assistencias:0,cleanSheets:3,status:"disponivel",draftedBy:null},
  {id:261,name:"Vinícius Silvestre",club:"BRA",position:"GOL",cost:0,projPoints:16.1,realPoints:0,jogos:2,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:262,name:"Luan Cândido",club:"BRA",position:"ZAG",cost:0,projPoints:47.8,realPoints:0,jogos:14,gols:0,assistencias:0,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:263,name:"Eduardo Santos",club:"BRA",position:"ZAG",cost:0,projPoints:50.1,realPoints:0,jogos:13,gols:0,assistencias:0,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:264,name:"Pedro Henrique BRA",club:"BRA",position:"ZAG",cost:0,projPoints:40.9,realPoints:0,jogos:8,gols:0,assistencias:0,cleanSheets:1,status:"disponivel",draftedBy:null},
  {id:265,name:"Juninho Capixaba",club:"BRA",position:"LAT",cost:0,projPoints:59.0,realPoints:0,jogos:15,gols:0,assistencias:2,cleanSheets:3,status:"disponivel",draftedBy:null},
  {id:266,name:"Andrés Hurtado",club:"BRA",position:"LAT",cost:0,projPoints:51.7,realPoints:0,jogos:12,gols:0,assistencias:1,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:267,name:"Jhon Jhon",club:"BRA",position:"MEI",cost:0,projPoints:73.6,realPoints:0,jogos:15,gols:1,assistencias:2,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:268,name:"Eric Ramires",club:"BRA",position:"MEI",cost:0,projPoints:53.4,realPoints:0,jogos:14,gols:0,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:269,name:"Matheus Fernandes",club:"BRA",position:"MEI",cost:0,projPoints:46.5,realPoints:0,jogos:12,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:270,name:"Eduardo Sasha",club:"BRA",position:"ATA",cost:0,projPoints:62.5,realPoints:0,jogos:15,gols:3,assistencias:2,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:271,name:"Thiago Borbas",club:"BRA",position:"ATA",cost:0,projPoints:57.3,realPoints:0,jogos:14,gols:3,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:272,name:"Ademir",club:"BRA",position:"ATA",cost:0,projPoints:49.3,realPoints:0,jogos:12,gols:2,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:273,name:"Vitinho BRA",club:"BRA",position:"ATA",cost:0,projPoints:44.9,realPoints:0,jogos:9,gols:1,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:280,name:"Walter",club:"MIR",position:"GOL",cost:0,projPoints:83.5,realPoints:0,jogos:15,gols:0,assistencias:0,cleanSheets:3,status:"disponivel",draftedBy:null},
  {id:281,name:"Alex Muralha",club:"MIR",position:"GOL",cost:0,projPoints:29.6,realPoints:0,jogos:3,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:282,name:"João Victor MIR",club:"MIR",position:"ZAG",cost:0,projPoints:50.8,realPoints:0,jogos:14,gols:0,assistencias:0,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:283,name:"Daniel Borges",club:"MIR",position:"LAT",cost:0,projPoints:54.9,realPoints:0,jogos:15,gols:0,assistencias:1,cleanSheets:3,status:"disponivel",draftedBy:null},
  {id:284,name:"Reinaldo MIR",club:"MIR",position:"LAT",cost:0,projPoints:39.1,realPoints:0,jogos:10,gols:0,assistencias:0,cleanSheets:1,status:"disponivel",draftedBy:null},
  {id:285,name:"Neto Moura",club:"MIR",position:"MEI",cost:0,projPoints:67.4,realPoints:0,jogos:15,gols:0,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:286,name:"Yuri Lara",club:"MIR",position:"MEI",cost:0,projPoints:59.4,realPoints:0,jogos:14,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:287,name:"Shaylon",club:"MIR",position:"MEI",cost:0,projPoints:54.4,realPoints:0,jogos:12,gols:0,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:288,name:"Antonio Galeano",club:"MIR",position:"MEI",cost:0,projPoints:54.8,realPoints:0,jogos:13,gols:0,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:289,name:"Alesson",club:"MIR",position:"ATA",cost:0,projPoints:79.2,realPoints:0,jogos:15,gols:5,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:290,name:"André Luís",club:"MIR",position:"ATA",cost:0,projPoints:54.0,realPoints:0,jogos:13,gols:3,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:291,name:"Tiquinho Soares",club:"MIR",position:"ATA",cost:0,projPoints:56.1,realPoints:0,jogos:12,gols:3,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:300,name:"Bento",club:"ATH",position:"GOL",cost:0,projPoints:113.9,realPoints:0,jogos:18,gols:0,assistencias:0,cleanSheets:6,status:"disponivel",draftedBy:null},
  {id:301,name:"Santos ATH",club:"ATH",position:"GOL",cost:0,projPoints:26.1,realPoints:0,jogos:1,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:302,name:"Benavídez",club:"ATH",position:"ZAG",cost:0,projPoints:61.1,realPoints:0,jogos:16,gols:0,assistencias:0,cleanSheets:5,status:"disponivel",draftedBy:null},
  {id:303,name:"Carlos Terán",club:"ATH",position:"ZAG",cost:0,projPoints:58.3,realPoints:0,jogos:15,gols:0,assistencias:0,cleanSheets:4,status:"disponivel",draftedBy:null},
  {id:304,name:"Gamarra",club:"ATH",position:"ZAG",cost:0,projPoints:49.0,realPoints:0,jogos:9,gols:0,assistencias:0,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:305,name:"Arthur Dias",club:"ATH",position:"LAT",cost:0,projPoints:60.8,realPoints:0,jogos:14,gols:0,assistencias:1,cleanSheets:4,status:"disponivel",draftedBy:null},
  {id:306,name:"Lucas Esquivel",club:"ATH",position:"LAT",cost:0,projPoints:64.6,realPoints:0,jogos:15,gols:0,assistencias:2,cleanSheets:4,status:"disponivel",draftedBy:null},
  {id:307,name:"Jadson",club:"ATH",position:"MEI",cost:0,projPoints:59.4,realPoints:0,jogos:14,gols:0,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:308,name:"Portilla",club:"ATH",position:"MEI",cost:0,projPoints:51.0,realPoints:0,jogos:13,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:309,name:"Bruno Zapelli",club:"ATH",position:"MEI",cost:0,projPoints:73.6,realPoints:0,jogos:15,gols:1,assistencias:2,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:310,name:"Felipinho",club:"ATH",position:"MEI",cost:0,projPoints:56.1,realPoints:0,jogos:12,gols:0,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:311,name:"Kevin Viveros",club:"ATH",position:"ATA",cost:0,projPoints:134.2,realPoints:0,jogos:18,gols:11,assistencias:2,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:312,name:"Julimar",club:"ATH",position:"ATA",cost:0,projPoints:61.7,realPoints:0,jogos:14,gols:3,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:313,name:"Mastriani",club:"ATH",position:"ATA",cost:0,projPoints:45.5,realPoints:0,jogos:11,gols:2,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:320,name:"Neto COT",club:"COT",position:"GOL",cost:0,projPoints:69.7,realPoints:0,jogos:16,gols:0,assistencias:0,cleanSheets:3,status:"disponivel",draftedBy:null},
  {id:321,name:"Alex COT",club:"COT",position:"GOL",cost:0,projPoints:16.1,realPoints:0,jogos:2,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:322,name:"Newton",club:"COT",position:"ZAG",cost:0,projPoints:48.6,realPoints:0,jogos:15,gols:0,assistencias:0,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:323,name:"Bastos",club:"COT",position:"ZAG",cost:0,projPoints:48.5,realPoints:0,jogos:13,gols:0,assistencias:0,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:324,name:"Tinga",club:"COT",position:"ZAG",cost:0,projPoints:42.1,realPoints:0,jogos:9,gols:0,assistencias:0,cleanSheets:1,status:"disponivel",draftedBy:null},
  {id:325,name:"Alex Telles",club:"COT",position:"LAT",cost:0,projPoints:59.4,realPoints:0,jogos:14,gols:0,assistencias:2,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:326,name:"Vitinho COT",club:"COT",position:"LAT",cost:0,projPoints:34.9,realPoints:0,jogos:10,gols:0,assistencias:0,cleanSheets:1,status:"disponivel",draftedBy:null},
  {id:327,name:"Allan COT",club:"COT",position:"MEI",cost:0,projPoints:54.9,realPoints:0,jogos:14,gols:0,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:328,name:"Danilo Avelar",club:"COT",position:"MEI",cost:0,projPoints:44.6,realPoints:0,jogos:11,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:329,name:"Artur COT",club:"COT",position:"ATA",cost:0,projPoints:66.7,realPoints:0,jogos:15,gols:4,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:330,name:"Pedro Rocha",club:"COT",position:"ATA",cost:0,projPoints:49.3,realPoints:0,jogos:12,gols:2,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:331,name:"Breno Lopes",club:"COT",position:"ATA",cost:0,projPoints:92.4,realPoints:0,jogos:16,gols:7,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:340,name:"Gabriel Vasconcellos",club:"CHE",position:"GOL",cost:0,projPoints:50.9,realPoints:0,jogos:16,gols:0,assistencias:0,cleanSheets:1,status:"disponivel",draftedBy:null},
  {id:341,name:"Camutanga",club:"CHE",position:"ZAG",cost:0,projPoints:41.9,realPoints:0,jogos:14,gols:0,assistencias:0,cleanSheets:1,status:"disponivel",draftedBy:null},
  {id:342,name:"Riccieli",club:"CHE",position:"ZAG",cost:0,projPoints:37.9,realPoints:0,jogos:12,gols:0,assistencias:0,cleanSheets:1,status:"disponivel",draftedBy:null},
  {id:343,name:"Matheuzinho CHE",club:"CHE",position:"LAT",cost:0,projPoints:37.5,realPoints:0,jogos:13,gols:0,assistencias:0,cleanSheets:1,status:"disponivel",draftedBy:null},
  {id:344,name:"Gabriel Baralhas",club:"CHE",position:"MEI",cost:0,projPoints:50.5,realPoints:0,jogos:14,gols:0,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:345,name:"Aitor Cantalapiedra",club:"CHE",position:"MEI",cost:0,projPoints:59.7,realPoints:0,jogos:15,gols:1,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:346,name:"Ronald CHE",club:"CHE",position:"MEI",cost:0,projPoints:34.4,realPoints:0,jogos:12,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:347,name:"Erick CHE",club:"CHE",position:"MEI",cost:0,projPoints:32.9,realPoints:0,jogos:10,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:348,name:"Renato Kayzer",club:"CHE",position:"ATA",cost:0,projPoints:46.9,realPoints:0,jogos:14,gols:3,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:349,name:"Carbone",club:"CHE",position:"ATA",cost:0,projPoints:45.8,realPoints:0,jogos:12,gols:2,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:360,name:"Vinícius REM",club:"REM",position:"GOL",cost:0,projPoints:51.2,realPoints:0,jogos:16,gols:0,assistencias:0,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:361,name:"Romário Bispo",club:"REM",position:"ZAG",cost:0,projPoints:49.3,realPoints:0,jogos:14,gols:0,assistencias:0,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:362,name:"Ligger",club:"REM",position:"ZAG",cost:0,projPoints:41.3,realPoints:0,jogos:12,gols:0,assistencias:0,cleanSheets:1,status:"disponivel",draftedBy:null},
  {id:363,name:"Carlinhos",club:"REM",position:"LAT",cost:0,projPoints:50.5,realPoints:0,jogos:14,gols:0,assistencias:1,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:364,name:"Jaderson",club:"REM",position:"MEI",cost:0,projPoints:54.9,realPoints:0,jogos:14,gols:0,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:365,name:"Pavani",club:"REM",position:"MEI",cost:0,projPoints:42.4,realPoints:0,jogos:12,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:366,name:"Ronald REM",club:"REM",position:"ATA",cost:0,projPoints:58.8,realPoints:0,jogos:14,gols:3,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:367,name:"Edinho",club:"REM",position:"ATA",cost:0,projPoints:40.6,realPoints:0,jogos:12,gols:2,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:370,name:"Lucas Arcanjo",club:"VIT",position:"GOL",cost:0,projPoints:49.9,realPoints:0,jogos:16,gols:0,assistencias:0,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:371,name:"Dalton",club:"VIT",position:"GOL",cost:0,projPoints:16.1,realPoints:0,jogos:2,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:372,name:"Caio Vinícius",club:"VIT",position:"ZAG",cost:0,projPoints:43.3,realPoints:0,jogos:14,gols:0,assistencias:0,cleanSheets:1,status:"disponivel",draftedBy:null},
  {id:373,name:"Wagner Leonardo VIT",club:"VIT",position:"ZAG",cost:0,projPoints:43.7,realPoints:0,jogos:13,gols:0,assistencias:0,cleanSheets:1,status:"disponivel",draftedBy:null},
  {id:374,name:"Willean Lepo",club:"VIT",position:"LAT",cost:0,projPoints:47.9,realPoints:0,jogos:15,gols:0,assistencias:1,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:375,name:"Raúl Cáceres",club:"VIT",position:"LAT",cost:0,projPoints:33.3,realPoints:0,jogos:13,gols:0,assistencias:0,cleanSheets:1,status:"disponivel",draftedBy:null},
  {id:376,name:"Léo Naldi",club:"VIT",position:"MEI",cost:0,projPoints:49.3,realPoints:0,jogos:14,gols:0,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:377,name:"Matheuzinho VIT",club:"VIT",position:"MEI",cost:0,projPoints:42.4,realPoints:0,jogos:12,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:378,name:"Osvaldo",club:"VIT",position:"ATA",cost:0,projPoints:46.9,realPoints:0,jogos:14,gols:3,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:379,name:"Janderson",club:"VIT",position:"ATA",cost:0,projPoints:38.9,realPoints:0,jogos:12,gols:2,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:380,name:"Alerrandro",club:"VIT",position:"ATA",cost:0,projPoints:59.3,realPoints:0,jogos:13,gols:3,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:390,name:"Gabriel Brazão SAN",club:"SAN",position:"GOL",cost:0,projPoints:51.4,realPoints:0,jogos:14,gols:0,assistencias:0,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:391,name:"João Paulo SAN",club:"SAN",position:"GOL",cost:0,projPoints:12.8,realPoints:0,jogos:3,gols:0,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:392,name:"Jair",club:"SAN",position:"ZAG",cost:0,projPoints:47.8,realPoints:0,jogos:14,gols:0,assistencias:0,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:393,name:"Gil",club:"SAN",position:"ZAG",cost:0,projPoints:50.1,realPoints:0,jogos:13,gols:0,assistencias:0,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:394,name:"JP Chermont",club:"SAN",position:"LAT",cost:0,projPoints:56.3,realPoints:0,jogos:15,gols:0,assistencias:2,cleanSheets:2,status:"disponivel",draftedBy:null},
  {id:395,name:"Escobar",club:"SAN",position:"MEI",cost:0,projPoints:54.9,realPoints:0,jogos:14,gols:0,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:396,name:"Giuliano",club:"SAN",position:"MEI",cost:0,projPoints:51.6,realPoints:0,jogos:13,gols:0,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:397,name:"Neymar",club:"SAN",position:"MEI",cost:0,projPoints:92.0,realPoints:0,jogos:12,gols:2,assistencias:4,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:398,name:"Wendel Silva",club:"SAN",position:"ATA",cost:0,projPoints:38.1,realPoints:0,jogos:13,gols:2,assistencias:0,cleanSheets:0,status:"disponivel",draftedBy:null},
  {id:399,name:"Tiquinho Soares SAN",club:"SAN",position:"ATA",cost:0,projPoints:67.1,realPoints:0,jogos:14,gols:4,assistencias:1,cleanSheets:0,status:"disponivel",draftedBy:null},
];