// =============================================
// ARENA FANTASY - Players Database
// Projeções baseadas em stats reais até rodada 18/2026
// Média de pontos/jogo × rodadas restantes + bônus disponibilidade
// =============================================

const PLAYERS_DATABASE = [
    { id: 1, name: "Carlos Miguel", club: "PAL", position: "GOL", cost: 0, projPoints: 142.3, realPoints: 0, jogos: 18, gols: 0, assistencias: 0, cleanSheets: 8, status: "disponivel", draftedBy: null },
    { id: 2, name: "Fábio", club: "FLU", position: "GOL", cost: 0, projPoints: 121.5, realPoints: 0, jogos: 17, gols: 0, assistencias: 0, cleanSheets: 7, status: "disponivel", draftedBy: null },
    { id: 3, name: "Bento", club: "ATH", position: "GOL", cost: 0, projPoints: 113.9, realPoints: 0, jogos: 18, gols: 0, assistencias: 0, cleanSheets: 6, status: "disponivel", draftedBy: null },
    { id: 4, name: "Rossi", club: "FLA", position: "GOL", cost: 0, projPoints: 93.8, realPoints: 0, jogos: 18, gols: 0, assistencias: 0, cleanSheets: 5, status: "disponivel", draftedBy: null },
    { id: 5, name: "Rafael", club: "SPFC", position: "GOL", cost: 0, projPoints: 76.9, realPoints: 0, jogos: 17, gols: 0, assistencias: 0, cleanSheets: 4, status: "disponivel", draftedBy: null },
    { id: 6, name: "Rochet", club: "INT", position: "GOL", cost: 0, projPoints: 69.2, realPoints: 0, jogos: 17, gols: 0, assistencias: 0, cleanSheets: 3, status: "disponivel", draftedBy: null },
    { id: 7, name: "Weverton", club: "GRE", position: "GOL", cost: 0, projPoints: 82.3, realPoints: 0, jogos: 17, gols: 0, assistencias: 0, cleanSheets: 4, status: "disponivel", draftedBy: null },
    { id: 8, name: "Cássio", club: "CRU", position: "GOL", cost: 0, projPoints: 68.0, realPoints: 0, jogos: 17, gols: 0, assistencias: 0, cleanSheets: 3, status: "disponivel", draftedBy: null },
    { id: 9, name: "Everson", club: "CAM", position: "GOL", cost: 0, projPoints: 68.0, realPoints: 0, jogos: 17, gols: 0, assistencias: 0, cleanSheets: 3, status: "disponivel", draftedBy: null },
    { id: 10, name: "Marcos Felipe", club: "BAH", position: "GOL", cost: 0, projPoints: 68.0, realPoints: 0, jogos: 17, gols: 0, assistencias: 0, cleanSheets: 3, status: "disponivel", draftedBy: null },
    { id: 11, name: "Cleiton", club: "BRA", position: "GOL", cost: 0, projPoints: 63.8, realPoints: 0, jogos: 17, gols: 0, assistencias: 0, cleanSheets: 3, status: "disponivel", draftedBy: null },
    { id: 12, name: "Léo Jardim", club: "VAS", position: "GOL", cost: 0, projPoints: 47.3, realPoints: 0, jogos: 16, gols: 0, assistencias: 0, cleanSheets: 2, status: "disponivel", draftedBy: null },
    { id: 13, name: "Hugo Souza", club: "COR", position: "GOL", cost: 0, projPoints: 47.3, realPoints: 0, jogos: 16, gols: 0, assistencias: 0, cleanSheets: 2, status: "disponivel", draftedBy: null },
    { id: 14, name: "John", club: "BOT", position: "GOL", cost: 0, projPoints: 71.0, realPoints: 0, jogos: 17, gols: 0, assistencias: 0, cleanSheets: 3, status: "disponivel", draftedBy: null },
    { id: 15, name: "Léo Pereira", club: "FLA", position: "ZAG", cost: 0, projPoints: 89.3, realPoints: 0, jogos: 17, gols: 1, assistencias: 1, cleanSheets: 5, status: "disponivel", draftedBy: null },
    { id: 16, name: "Léo Ortiz", club: "FLA", position: "ZAG", cost: 0, projPoints: 82.5, realPoints: 0, jogos: 16, gols: 0, assistencias: 2, cleanSheets: 5, status: "disponivel", draftedBy: null },
    { id: 17, name: "Gustavo Gómez", club: "PAL", position: "ZAG", cost: 0, projPoints: 99.6, realPoints: 0, jogos: 18, gols: 1, assistencias: 0, cleanSheets: 8, status: "disponivel", draftedBy: null },
    { id: 18, name: "Murilo", club: "PAL", position: "ZAG", cost: 0, projPoints: 93.0, realPoints: 0, jogos: 17, gols: 0, assistencias: 1, cleanSheets: 8, status: "disponivel", draftedBy: null },
    { id: 19, name: "Gabriel Xavier", club: "BAH", position: "ZAG", cost: 0, projPoints: 75.6, realPoints: 0, jogos: 17, gols: 1, assistencias: 1, cleanSheets: 3, status: "disponivel", draftedBy: null },
    { id: 20, name: "Fabrício Bruno", club: "CRU", position: "ZAG", cost: 0, projPoints: 67.9, realPoints: 0, jogos: 17, gols: 0, assistencias: 1, cleanSheets: 3, status: "disponivel", draftedBy: null },
    { id: 21, name: "Alexander Barboza", club: "BOT", position: "ZAG", cost: 0, projPoints: 62.8, realPoints: 0, jogos: 17, gols: 1, assistencias: 0, cleanSheets: 3, status: "disponivel", draftedBy: null },
    { id: 22, name: "Félix Torres", club: "INT", position: "ZAG", cost: 0, projPoints: 71.5, realPoints: 0, jogos: 16, gols: 1, assistencias: 0, cleanSheets: 3, status: "disponivel", draftedBy: null },
    { id: 23, name: "Ruan", club: "CAM", position: "ZAG", cost: 0, projPoints: 53.5, realPoints: 0, jogos: 16, gols: 0, assistencias: 0, cleanSheets: 3, status: "disponivel", draftedBy: null },
    { id: 24, name: "Vitão", club: "INT", position: "ZAG", cost: 0, projPoints: 57.5, realPoints: 0, jogos: 17, gols: 0, assistencias: 0, cleanSheets: 3, status: "disponivel", draftedBy: null },
    { id: 25, name: "Arboleda", club: "SPFC", position: "ZAG", cost: 0, projPoints: 54.8, realPoints: 0, jogos: 16, gols: 0, assistencias: 0, cleanSheets: 4, status: "disponivel", draftedBy: null },
    { id: 26, name: "Bruno Fuchs", club: "PAL", position: "ZAG", cost: 0, projPoints: 84.7, realPoints: 0, jogos: 15, gols: 0, assistencias: 0, cleanSheets: 8, status: "disponivel", draftedBy: null },
    { id: 27, name: "Kannemann", club: "GRE", position: "ZAG", cost: 0, projPoints: 61.1, realPoints: 0, jogos: 15, gols: 0, assistencias: 0, cleanSheets: 4, status: "disponivel", draftedBy: null },
    { id: 28, name: "Emerson Royal", club: "FLA", position: "LAT", cost: 0, projPoints: 84.9, realPoints: 0, jogos: 16, gols: 0, assistencias: 3, cleanSheets: 5, status: "disponivel", draftedBy: null },
    { id: 29, name: "Ayrton Lucas", club: "FLA", position: "LAT", cost: 0, projPoints: 87.5, realPoints: 0, jogos: 15, gols: 1, assistencias: 2, cleanSheets: 5, status: "disponivel", draftedBy: null },
    { id: 30, name: "Piquerez", club: "PAL", position: "LAT", cost: 0, projPoints: 99.3, realPoints: 0, jogos: 17, gols: 1, assistencias: 3, cleanSheets: 8, status: "disponivel", draftedBy: null },
    { id: 31, name: "Rodinei", club: "GRE", position: "LAT", cost: 0, projPoints: 78.2, realPoints: 0, jogos: 17, gols: 0, assistencias: 5, cleanSheets: 4, status: "disponivel", draftedBy: null },
    { id: 32, name: "Guilherme Arana", club: "FLU", position: "LAT", cost: 0, projPoints: 78.6, realPoints: 0, jogos: 16, gols: 0, assistencias: 2, cleanSheets: 7, status: "disponivel", draftedBy: null },
    { id: 33, name: "Lucas Piton", club: "VAS", position: "LAT", cost: 0, projPoints: 61.0, realPoints: 0, jogos: 17, gols: 1, assistencias: 2, cleanSheets: 2, status: "disponivel", draftedBy: null },
    { id: 34, name: "William", club: "CRU", position: "LAT", cost: 0, projPoints: 60.8, realPoints: 0, jogos: 16, gols: 0, assistencias: 2, cleanSheets: 3, status: "disponivel", draftedBy: null },
    { id: 35, name: "Bernabei", club: "INT", position: "LAT", cost: 0, projPoints: 52.0, realPoints: 0, jogos: 17, gols: 0, assistencias: 1, cleanSheets: 3, status: "disponivel", draftedBy: null },
    { id: 36, name: "Luciano Juba", club: "BAH", position: "LAT", cost: 0, projPoints: 118.8, realPoints: 0, jogos: 17, gols: 7, assistencias: 2, cleanSheets: 3, status: "disponivel", draftedBy: null },
    { id: 37, name: "Renan Lodi", club: "CAM", position: "LAT", cost: 0, projPoints: 56.1, realPoints: 0, jogos: 16, gols: 0, assistencias: 2, cleanSheets: 3, status: "disponivel", draftedBy: null },
    { id: 38, name: "Lucas Esquivel", club: "ATH", position: "LAT", cost: 0, projPoints: 68.4, realPoints: 0, jogos: 17, gols: 0, assistencias: 2, cleanSheets: 6, status: "disponivel", draftedBy: null },
    { id: 39, name: "Marcos Rocha", club: "GRE", position: "LAT", cost: 0, projPoints: 56.1, realPoints: 0, jogos: 16, gols: 0, assistencias: 1, cleanSheets: 4, status: "disponivel", draftedBy: null },
    { id: 40, name: "Caio Paulista", club: "GRE", position: "LAT", cost: 0, projPoints: 55.6, realPoints: 0, jogos: 15, gols: 0, assistencias: 1, cleanSheets: 4, status: "disponivel", draftedBy: null },
    { id: 41, name: "Andreas Pereira", club: "FLA", position: "MEI", cost: 0, projPoints: 126.0, realPoints: 0, jogos: 18, gols: 3, assistencias: 8, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 42, name: "Arrascaeta", club: "FLA", position: "MEI", cost: 0, projPoints: 117.5, realPoints: 0, jogos: 16, gols: 4, assistencias: 5, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 43, name: "Raphael Veiga", club: "PAL", position: "MEI", cost: 0, projPoints: 111.5, realPoints: 0, jogos: 17, gols: 3, assistencias: 6, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 44, name: "Gerson", club: "FLA", position: "MEI", cost: 0, projPoints: 115.8, realPoints: 0, jogos: 17, gols: 2, assistencias: 4, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 45, name: "Alan Patrick", club: "INT", position: "MEI", cost: 0, projPoints: 92.4, realPoints: 0, jogos: 17, gols: 2, assistencias: 4, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 46, name: "Rodrigo Garro", club: "COR", position: "MEI", cost: 0, projPoints: 88.8, realPoints: 0, jogos: 16, gols: 3, assistencias: 2, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 47, name: "Marlon Freitas", club: "PAL", position: "MEI", cost: 0, projPoints: 107.8, realPoints: 0, jogos: 17, gols: 1, assistencias: 2, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 48, name: "Matheus Pereira", club: "CRU", position: "MEI", cost: 0, projPoints: 86.2, realPoints: 0, jogos: 17, gols: 2, assistencias: 3, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 49, name: "De la Cruz", club: "FLA", position: "MEI", cost: 0, projPoints: 93.1, realPoints: 0, jogos: 15, gols: 2, assistencias: 3, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 50, name: "Cristaldo", club: "GRE", position: "MEI", cost: 0, projPoints: 85.9, realPoints: 0, jogos: 16, gols: 2, assistencias: 3, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 51, name: "Claudinho", club: "BRA", position: "MEI", cost: 0, projPoints: 80.8, realPoints: 0, jogos: 17, gols: 2, assistencias: 3, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 52, name: "Bernard", club: "CAM", position: "MEI", cost: 0, projPoints: 67.4, realPoints: 0, jogos: 15, gols: 2, assistencias: 1, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 53, name: "Cauly", club: "BAH", position: "MEI", cost: 0, projPoints: 63.2, realPoints: 0, jogos: 15, gols: 1, assistencias: 2, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 54, name: "Luciano", club: "SPFC", position: "MEI", cost: 0, projPoints: 89.8, realPoints: 0, jogos: 16, gols: 3, assistencias: 2, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 55, name: "Neymar", club: "SAN", position: "MEI", cost: 0, projPoints: 90.2, realPoints: 0, jogos: 12, gols: 2, assistencias: 4, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 56, name: "Gabriel Menino", club: "PAL", position: "MEI", cost: 0, projPoints: 95.8, realPoints: 0, jogos: 15, gols: 1, assistencias: 4, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 57, name: "Ganso", club: "FLU", position: "MEI", cost: 0, projPoints: 63.9, realPoints: 0, jogos: 15, gols: 1, assistencias: 2, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 58, name: "Cuello", club: "CAM", position: "MEI", cost: 0, projPoints: 70.5, realPoints: 0, jogos: 16, gols: 2, assistencias: 2, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 59, name: "Thiago Maia", club: "INT", position: "MEI", cost: 0, projPoints: 78.6, realPoints: 0, jogos: 16, gols: 0, assistencias: 1, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 60, name: "Payet", club: "VAS", position: "MEI", cost: 0, projPoints: 70.1, realPoints: 0, jogos: 14, gols: 2, assistencias: 2, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 61, name: "Monsalve", club: "GRE", position: "MEI", cost: 0, projPoints: 64.0, realPoints: 0, jogos: 16, gols: 1, assistencias: 2, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 62, name: "Lucas Silva", club: "CRU", position: "MEI", cost: 0, projPoints: 72.9, realPoints: 0, jogos: 15, gols: 0, assistencias: 2, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 63, name: "Kevin Viveros", club: "ATH", position: "ATA", cost: 0, projPoints: 134.2, realPoints: 0, jogos: 18, gols: 11, assistencias: 2, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 64, name: "Pedro", club: "FLA", position: "ATA", cost: 0, projPoints: 133.2, realPoints: 0, jogos: 17, gols: 10, assistencias: 3, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 65, name: "Carlos Vinícius", club: "GRE", position: "ATA", cost: 0, projPoints: 108.5, realPoints: 0, jogos: 17, gols: 9, assistencias: 1, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 66, name: "John Kennedy", club: "FLU", position: "ATA", cost: 0, projPoints: 102.4, realPoints: 0, jogos: 17, gols: 8, assistencias: 1, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 67, name: "Arthur Cabral", club: "BOT", position: "ATA", cost: 0, projPoints: 91.1, realPoints: 0, jogos: 16, gols: 7, assistencias: 1, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 68, name: "Breno Lopes", club: "COT", position: "ATA", cost: 0, projPoints: 85.1, realPoints: 0, jogos: 17, gols: 7, assistencias: 1, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 69, name: "Estêvão", club: "PAL", position: "ATA", cost: 0, projPoints: 103.2, realPoints: 0, jogos: 17, gols: 7, assistencias: 2, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 70, name: "John Kennedy FLU", club: "FLU", position: "ATA", cost: 0, projPoints: 102.4, realPoints: 0, jogos: 17, gols: 8, assistencias: 1, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 71, name: "Hulk", club: "FLU", position: "ATA", cost: 0, projPoints: 86.4, realPoints: 0, jogos: 14, gols: 5, assistencias: 1, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 72, name: "Vitor Roque", club: "PAL", position: "ATA", cost: 0, projPoints: 91.1, realPoints: 0, jogos: 16, gols: 6, assistencias: 1, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 73, name: "Yuri Alberto", club: "COR", position: "ATA", cost: 0, projPoints: 76.2, realPoints: 0, jogos: 16, gols: 5, assistencias: 2, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 74, name: "Kaio Jorge", club: "CRU", position: "ATA", cost: 0, projPoints: 74.0, realPoints: 0, jogos: 17, gols: 5, assistencias: 2, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 75, name: "Savarino", club: "FLU", position: "ATA", cost: 0, projPoints: 84.9, realPoints: 0, jogos: 16, gols: 4, assistencias: 3, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 76, name: "Rony", club: "FLU", position: "ATA", cost: 0, projPoints: 72.8, realPoints: 0, jogos: 17, gols: 5, assistencias: 1, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 77, name: "Luiz Henrique", club: "BOT", position: "ATA", cost: 0, projPoints: 80.6, realPoints: 0, jogos: 15, gols: 4, assistencias: 3, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 78, name: "Calleri", club: "SPFC", position: "ATA", cost: 0, projPoints: 62.4, realPoints: 0, jogos: 16, gols: 4, assistencias: 1, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 79, name: "Rayan", club: "VAS", position: "ATA", cost: 0, projPoints: 68.4, realPoints: 0, jogos: 16, gols: 4, assistencias: 2, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 80, name: "Borré", club: "INT", position: "ATA", cost: 0, projPoints: 57.2, realPoints: 0, jogos: 16, gols: 3, assistencias: 2, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 81, name: "Claudinho BRA", club: "BRA", position: "ATA", cost: 0, projPoints: 61.4, realPoints: 0, jogos: 17, gols: 3, assistencias: 3, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 82, name: "Memphis Depay", club: "COR", position: "ATA", cost: 0, projPoints: 61.1, realPoints: 0, jogos: 14, gols: 3, assistencias: 2, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 83, name: "Ademir", club: "BRA", position: "ATA", cost: 0, projPoints: 59.8, realPoints: 0, jogos: 16, gols: 4, assistencias: 1, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 84, name: "Danilo BOT", club: "BOT", position: "ATA", cost: 0, projPoints: 94.2, realPoints: 0, jogos: 17, gols: 7, assistencias: 2, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 85, name: "Neymar SAN", club: "SAN", position: "ATA", cost: 0, projPoints: 68.2, realPoints: 0, jogos: 12, gols: 3, assistencias: 2, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 86, name: "Alex Sandro", club: "FLA", position: "LAT", cost: 0, projPoints: 10, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 87, name: "Jefté", club: "PAL", position: "LAT", cost: 0, projPoints: 10, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 88, name: "Agustín Giay", club: "PAL", position: "LAT", cost: 0, projPoints: 12, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 89, name: "Diogo Barbosa", club: "FLU", position: "LAT", cost: 0, projPoints: 10, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 90, name: "Samuel Xavier", club: "FLU", position: "LAT", cost: 0, projPoints: 10, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 91, name: "Puma Rodríguez", club: "VAS", position: "LAT", cost: 0, projPoints: 10, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 92, name: "Bruno Gomes", club: "INT", position: "LAT", cost: 0, projPoints: 8, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 93, name: "Matheuzinho", club: "COR", position: "LAT", cost: 0, projPoints: 8, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 94, name: "Matheus Bidu", club: "COR", position: "LAT", cost: 0, projPoints: 8, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 95, name: "Preciado", club: "CAM", position: "LAT", cost: 0, projPoints: 8, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 96, name: "Arthur Dias", club: "ATH", position: "LAT", cost: 0, projPoints: 8, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 97, name: "Jorginho", club: "FLA", position: "MEI", cost: 0, projPoints: 12, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 98, name: "Pulgar", club: "FLA", position: "MEI", cost: 0, projPoints: 10, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 99, name: "Allan", club: "PAL", position: "MEI", cost: 0, projPoints: 10, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 100, name: "Felipe Anderson", club: "PAL", position: "MEI", cost: 0, projPoints: 10, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 101, name: "Jhon Arias", club: "PAL", position: "MEI", cost: 0, projPoints: 12, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 102, name: "Mauricio", club: "PAL", position: "MEI", cost: 0, projPoints: 11, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 103, name: "Cristian Medina", club: "BOT", position: "MEI", cost: 0, projPoints: 11, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 104, name: "Edenilson", club: "GRE", position: "MEI", cost: 0, projPoints: 10, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 105, name: "Dodi", club: "GRE", position: "MEI", cost: 0, projPoints: 10, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 106, name: "Martinelli", club: "FLU", position: "MEI", cost: 0, projPoints: 11, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 107, name: "Hércules", club: "FLU", position: "MEI", cost: 0, projPoints: 10, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 108, name: "Hugo Moura", club: "VAS", position: "MEI", cost: 0, projPoints: 8, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 109, name: "Marcos Antonio", club: "SPFC", position: "MEI", cost: 0, projPoints: 9, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 110, name: "Charles", club: "COR", position: "MEI", cost: 0, projPoints: 10, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 111, name: "Raniele", club: "COR", position: "MEI", cost: 0, projPoints: 9, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 112, name: "Oscar", club: "SPFC", position: "MEI", cost: 0, projPoints: 9, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 113, name: "Danielzinho", club: "SPFC", position: "MEI", cost: 0, projPoints: 9, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 114, name: "Everton Ribeiro", club: "BAH", position: "MEI", cost: 0, projPoints: 10, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 115, name: "Michel Araújo", club: "BAH", position: "MEI", cost: 0, projPoints: 9, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 116, name: "Acevedo", club: "BAH", position: "MEI", cost: 0, projPoints: 9, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 117, name: "Jadson", club: "ATH", position: "MEI", cost: 0, projPoints: 10, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 118, name: "Bruno Zapelli", club: "ATH", position: "MEI", cost: 0, projPoints: 11, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 119, name: "Neto Moura", club: "MIR", position: "MEI", cost: 0, projPoints: 9, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 120, name: "Alesson", club: "MIR", position: "ATA", cost: 0, projPoints: 12, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 121, name: "André Luís", club: "MIR", position: "ATA", cost: 0, projPoints: 10, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 122, name: "Julimar", club: "ATH", position: "ATA", cost: 0, projPoints: 10, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 123, name: "Willian José", club: "BAH", position: "ATA", cost: 0, projPoints: 10, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 124, name: "Iago", club: "BAH", position: "ATA", cost: 0, projPoints: 9, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 125, name: "Eduardo Sasha", club: "BRA", position: "ATA", cost: 0, projPoints: 9, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 126, name: "Thiago Borbas", club: "BRA", position: "ATA", cost: 0, projPoints: 9, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 127, name: "André Silva", club: "SPFC", position: "ATA", cost: 0, projPoints: 9, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 128, name: "Bruno Henrique", club: "FLA", position: "ATA", cost: 0, projPoints: 9, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 129, name: "Samuel Lino", club: "FLA", position: "ATA", cost: 0, projPoints: 9, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 130, name: "Ramón Sosa", club: "PAL", position: "ATA", cost: 0, projPoints: 9, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 131, name: "Flaco López", club: "PAL", position: "ATA", cost: 0, projPoints: 9, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 132, name: "Osvaldo", club: "VIT", position: "ATA", cost: 0, projPoints: 9, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 133, name: "Tiquinho Soares", club: "SAN", position: "ATA", cost: 0, projPoints: 10, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 134, name: "Wendel Silva", club: "SAN", position: "ATA", cost: 0, projPoints: 8, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 135, name: "Matheus Donelli", club: "COR", position: "GOL", cost: 0, projPoints: 8, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 136, name: "Dalton", club: "VIT", position: "GOL", cost: 0, projPoints: 6, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 137, name: "Vinícius", club: "REM", position: "GOL", cost: 0, projPoints: 6, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 138, name: "Gabriel Vasconcellos", club: "CHE", position: "GOL", cost: 0, projPoints: 6, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 139, name: "Neto", club: "COT", position: "GOL", cost: 0, projPoints: 8, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 140, name: "Alex Muralha", club: "MIR", position: "GOL", cost: 0, projPoints: 6, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 141, name: "João Victor", club: "FLA", position: "ZAG", cost: 0, projPoints: 9, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 142, name: "Ignácio", club: "FLU", position: "ZAG", cost: 0, projPoints: 9, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 143, name: "Maicon", club: "VAS", position: "ZAG", cost: 0, projPoints: 8, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 144, name: "Wagner Leonardo", club: "GRE", position: "ZAG", cost: 0, projPoints: 8, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 145, name: "Jemmes", club: "FLU", position: "ZAG", cost: 0, projPoints: 8, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 146, name: "Freytes", club: "FLU", position: "ZAG", cost: 0, projPoints: 8, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 147, name: "Jonathan Jesus", club: "CRU", position: "ZAG", cost: 0, projPoints: 8, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 148, name: "Newton", club: "COT", position: "ZAG", cost: 0, projPoints: 7, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 149, name: "Bastos", club: "COT", position: "ZAG", cost: 0, projPoints: 7, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 150, name: "Camutanga", club: "CHE", position: "ZAG", cost: 0, projPoints: 6, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 151, name: "Vitor Hugo", club: "CAM", position: "ZAG", cost: 0, projPoints: 8, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 152, name: "Mercado", club: "INT", position: "ZAG", cost: 0, projPoints: 8, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
    { id: 153, name: "Romário Bispo", club: "REM", position: "ZAG", cost: 0, projPoints: 6, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, cleanSheets: 0, status: "disponivel", draftedBy: null },
];
