const PLAYERS_DATABASE = [
    { id: 1, name: "Rossi", club: "FLA", position: "GOL", cost: 0, projPoints: 88.2, realPoints: 0, jogos: 18, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 2, name: "Bento", club: "ATH", position: "GOL", cost: 0, projPoints: 93.6, realPoints: 0, jogos: 18, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 3, name: "John", club: "BOT", position: "GOL", cost: 0, projPoints: 68.9, realPoints: 0, jogos: 17, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 4, name: "Fábio", club: "FLU", position: "GOL", cost: 0, projPoints: 95.5, realPoints: 0, jogos: 16, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 5, name: "Rafael", club: "SPFC", position: "GOL", cost: 0, projPoints: 64.9, realPoints: 0, jogos: 17, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 6, name: "Carlos Miguel", club: "PAL", position: "GOL", cost: 0, projPoints: 128.7, realPoints: 0, jogos: 18, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 7, name: "Cássio", club: "CRU", position: "GOL", cost: 0, projPoints: 66.8, realPoints: 0, jogos: 16, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 8, name: "Weverton", club: "GRE", position: "GOL", cost: 0, projPoints: 71.3, realPoints: 0, jogos: 17, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 9, name: "Everson", club: "CAM", position: "GOL", cost: 0, projPoints: 66.1, realPoints: 0, jogos: 17, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 10, name: "Léo Jardim", club: "VAS", position: "GOL", cost: 0, projPoints: 52.5, realPoints: 0, jogos: 16, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 11, name: "Rochet", club: "INT", position: "GOL", cost: 0, projPoints: 66.1, realPoints: 0, jogos: 17, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 12, name: "Marcos Felipe", club: "BAH", position: "GOL", cost: 0, projPoints: 64.9, realPoints: 0, jogos: 17, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 13, name: "Hugo Souza", club: "COR", position: "GOL", cost: 0, projPoints: 45.2, realPoints: 0, jogos: 16, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 14, name: "Cleiton", club: "BRA", position: "GOL", cost: 0, projPoints: 53.6, realPoints: 0, jogos: 17, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 15, name: "Gabriel Brazão", club: "BOT", position: "GOL", cost: 0, projPoints: -24.0, realPoints: 0, jogos: 1, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 16, name: "Léo Pereira", club: "FLA", position: "ZAG", cost: 0, projPoints: 87.1, realPoints: 0, jogos: 17, gols: 1, assistencias: 1, status: "disponivel", draftedBy: null },
    { id: 17, name: "Léo Ortiz", club: "FLA", position: "ZAG", cost: 0, projPoints: 80.9, realPoints: 0, jogos: 16, gols: 0, assistencias: 2, status: "disponivel", draftedBy: null },
    { id: 18, name: "Gustavo Gómez", club: "PAL", position: "ZAG", cost: 0, projPoints: 96.6, realPoints: 0, jogos: 18, gols: 1, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 19, name: "Murilo", club: "PAL", position: "ZAG", cost: 0, projPoints: 90.6, realPoints: 0, jogos: 17, gols: 0, assistencias: 1, status: "disponivel", draftedBy: null },
    { id: 20, name: "Alexander Barboza", club: "BOT", position: "ZAG", cost: 0, projPoints: 62.9, realPoints: 0, jogos: 17, gols: 1, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 21, name: "Fabrício Bruno", club: "CRU", position: "ZAG", cost: 0, projPoints: 66.6, realPoints: 0, jogos: 17, gols: 0, assistencias: 1, status: "disponivel", draftedBy: null },
    { id: 22, name: "João Victor", club: "FLA", position: "ZAG", cost: 0, projPoints: 68.5, realPoints: 0, jogos: 12, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 23, name: "Ruan", club: "CAM", position: "ZAG", cost: 0, projPoints: 54.4, realPoints: 0, jogos: 16, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 24, name: "Vitão", club: "INT", position: "ZAG", cost: 0, projPoints: 56.7, realPoints: 0, jogos: 17, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 25, name: "Arboleda", club: "SPFC", position: "ZAG", cost: 0, projPoints: 50.6, realPoints: 0, jogos: 16, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 26, name: "Gabriel Xavier", club: "BAH", position: "ZAG", cost: 0, projPoints: 74.0, realPoints: 0, jogos: 17, gols: 1, assistencias: 1, status: "disponivel", draftedBy: null },
    { id: 27, name: "Félix Torres", club: "INT", position: "ZAG", cost: 0, projPoints: 70.4, realPoints: 0, jogos: 16, gols: 1, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 28, name: "Emerson Royal", club: "FLA", position: "LAT", cost: 0, projPoints: 83.1, realPoints: 0, jogos: 16, gols: 0, assistencias: 3, status: "disponivel", draftedBy: null },
    { id: 29, name: "Ayrton Lucas", club: "FLA", position: "LAT", cost: 0, projPoints: 86.0, realPoints: 0, jogos: 15, gols: 1, assistencias: 2, status: "disponivel", draftedBy: null },
    { id: 30, name: "Piquerez", club: "PAL", position: "LAT", cost: 0, projPoints: 96.6, realPoints: 0, jogos: 17, gols: 1, assistencias: 3, status: "disponivel", draftedBy: null },
    { id: 31, name: "Rodinei", club: "GRE", position: "LAT", cost: 0, projPoints: 74.1, realPoints: 0, jogos: 17, gols: 0, assistencias: 5, status: "disponivel", draftedBy: null },
    { id: 32, name: "Guilherme Arana", club: "FLU", position: "LAT", cost: 0, projPoints: 69.0, realPoints: 0, jogos: 16, gols: 0, assistencias: 2, status: "disponivel", draftedBy: null },
    { id: 33, name: "Lucas Piton", club: "VAS", position: "LAT", cost: 0, projPoints: 60.6, realPoints: 0, jogos: 17, gols: 1, assistencias: 2, status: "disponivel", draftedBy: null },
    { id: 34, name: "William", club: "CRU", position: "LAT", cost: 0, projPoints: 60.1, realPoints: 0, jogos: 16, gols: 0, assistencias: 2, status: "disponivel", draftedBy: null },
    { id: 35, name: "Bernabei", club: "INT", position: "LAT", cost: 0, projPoints: 51.4, realPoints: 0, jogos: 17, gols: 0, assistencias: 1, status: "disponivel", draftedBy: null },
    { id: 36, name: "Luciano Juba", club: "BAH", position: "LAT", cost: 0, projPoints: 115.2, realPoints: 0, jogos: 17, gols: 7, assistencias: 2, status: "disponivel", draftedBy: null },
    { id: 37, name: "Renan Lodi", club: "CAM", position: "LAT", cost: 0, projPoints: 56.9, realPoints: 0, jogos: 16, gols: 0, assistencias: 2, status: "disponivel", draftedBy: null },
    { id: 38, name: "Lucas Esquivel", club: "ATH", position: "LAT", cost: 0, projPoints: 61.8, realPoints: 0, jogos: 17, gols: 0, assistencias: 2, status: "disponivel", draftedBy: null },
    { id: 39, name: "Andreas Pereira", club: "FLA", position: "MEI", cost: 0, projPoints: 118.9, realPoints: 0, jogos: 18, gols: 3, assistencias: 8, status: "disponivel", draftedBy: null },
    { id: 40, name: "Arrascaeta", club: "FLA", position: "MEI", cost: 0, projPoints: 111.2, realPoints: 0, jogos: 16, gols: 4, assistencias: 5, status: "disponivel", draftedBy: null },
    { id: 41, name: "Raphael Veiga", club: "PAL", position: "MEI", cost: 0, projPoints: 106.5, realPoints: 0, jogos: 17, gols: 3, assistencias: 6, status: "disponivel", draftedBy: null },
    { id: 42, name: "Gerson", club: "FLA", position: "MEI", cost: 0, projPoints: 109.4, realPoints: 0, jogos: 17, gols: 2, assistencias: 4, status: "disponivel", draftedBy: null },
    { id: 43, name: "Alan Patrick", club: "INT", position: "MEI", cost: 0, projPoints: 88.2, realPoints: 0, jogos: 17, gols: 2, assistencias: 4, status: "disponivel", draftedBy: null },
    { id: 44, name: "Rodrigo Garro", club: "COR", position: "MEI", cost: 0, projPoints: 85.0, realPoints: 0, jogos: 16, gols: 3, assistencias: 2, status: "disponivel", draftedBy: null },
    { id: 45, name: "Marlon Freitas", club: "PAL", position: "MEI", cost: 0, projPoints: 102.9, realPoints: 0, jogos: 17, gols: 1, assistencias: 2, status: "disponivel", draftedBy: null },
    { id: 46, name: "Matheus Pereira", club: "CRU", position: "MEI", cost: 0, projPoints: 82.4, realPoints: 0, jogos: 17, gols: 2, assistencias: 3, status: "disponivel", draftedBy: null },
    { id: 47, name: "De la Cruz", club: "FLA", position: "MEI", cost: 0, projPoints: 88.0, realPoints: 0, jogos: 15, gols: 2, assistencias: 3, status: "disponivel", draftedBy: null },
    { id: 48, name: "Cristaldo", club: "GRE", position: "MEI", cost: 0, projPoints: 82.2, realPoints: 0, jogos: 16, gols: 2, assistencias: 3, status: "disponivel", draftedBy: null },
    { id: 49, name: "Monsalve", club: "GRE", position: "MEI", cost: 0, projPoints: 61.2, realPoints: 0, jogos: 16, gols: 1, assistencias: 2, status: "disponivel", draftedBy: null },
    { id: 50, name: "Claudinho", club: "BRA", position: "MEI", cost: 0, projPoints: 77.2, realPoints: 0, jogos: 17, gols: 2, assistencias: 3, status: "disponivel", draftedBy: null },
    { id: 51, name: "Bernard", club: "CAM", position: "MEI", cost: 0, projPoints: 66.0, realPoints: 0, jogos: 15, gols: 2, assistencias: 1, status: "disponivel", draftedBy: null },
    { id: 52, name: "Cauly", club: "BAH", position: "MEI", cost: 0, projPoints: 60.7, realPoints: 0, jogos: 15, gols: 1, assistencias: 2, status: "disponivel", draftedBy: null },
    { id: 53, name: "Luciano", club: "SPFC", position: "MEI", cost: 0, projPoints: 84.8, realPoints: 0, jogos: 16, gols: 3, assistencias: 2, status: "disponivel", draftedBy: null },
    { id: 54, name: "Neymar", club: "SAN", position: "MEI", cost: 0, projPoints: 89.0, realPoints: 0, jogos: 12, gols: 2, assistencias: 4, status: "disponivel", draftedBy: null },
    { id: 55, name: "Gabriel Menino", club: "PAL", position: "MEI", cost: 0, projPoints: 92.0, realPoints: 0, jogos: 15, gols: 1, assistencias: 4, status: "disponivel", draftedBy: null },
    { id: 56, name: "Ganso", club: "FLU", position: "MEI", cost: 0, projPoints: 60.0, realPoints: 0, jogos: 15, gols: 1, assistencias: 2, status: "disponivel", draftedBy: null },
    { id: 57, name: "Payet", club: "VAS", position: "MEI", cost: 0, projPoints: 68.9, realPoints: 0, jogos: 14, gols: 2, assistencias: 2, status: "disponivel", draftedBy: null },
    { id: 58, name: "Cuello", club: "CAM", position: "MEI", cost: 0, projPoints: 68.8, realPoints: 0, jogos: 16, gols: 2, assistencias: 2, status: "disponivel", draftedBy: null },
    { id: 59, name: "Thiago Maia", club: "INT", position: "MEI", cost: 0, projPoints: 75.2, realPoints: 0, jogos: 16, gols: 0, assistencias: 1, status: "disponivel", draftedBy: null },
    { id: 60, name: "Kevin Viveros", club: "ATH", position: "ATA", cost: 0, projPoints: 126.7, realPoints: 0, jogos: 18, gols: 11, assistencias: 2, status: "disponivel", draftedBy: null },
    { id: 61, name: "Pedro", club: "FLA", position: "ATA", cost: 0, projPoints: 126.0, realPoints: 0, jogos: 17, gols: 10, assistencias: 3, status: "disponivel", draftedBy: null },
    { id: 62, name: "Carlos Vinícius", club: "GRE", position: "ATA", cost: 0, projPoints: 103.6, realPoints: 0, jogos: 17, gols: 9, assistencias: 1, status: "disponivel", draftedBy: null },
    { id: 63, name: "John Kennedy", club: "FLU", position: "ATA", cost: 0, projPoints: 96.6, realPoints: 0, jogos: 17, gols: 8, assistencias: 1, status: "disponivel", draftedBy: null },
    { id: 64, name: "Arthur Cabral", club: "BOT", position: "ATA", cost: 0, projPoints: 88.5, realPoints: 0, jogos: 16, gols: 7, assistencias: 1, status: "disponivel", draftedBy: null },
    { id: 65, name: "Danilo BOT", club: "BOT", position: "ATA", cost: 0, projPoints: 91.2, realPoints: 0, jogos: 17, gols: 7, assistencias: 2, status: "disponivel", draftedBy: null },
    { id: 66, name: "Breno Lopes", club: "COT", position: "ATA", cost: 0, projPoints: 82.5, realPoints: 0, jogos: 17, gols: 7, assistencias: 1, status: "disponivel", draftedBy: null },
    { id: 67, name: "Estêvão", club: "PAL", position: "ATA", cost: 0, projPoints: 98.6, realPoints: 0, jogos: 17, gols: 7, assistencias: 2, status: "disponivel", draftedBy: null },
    { id: 68, name: "Hulk", club: "FLU", position: "ATA", cost: 0, projPoints: 81.7, realPoints: 0, jogos: 14, gols: 5, assistencias: 1, status: "disponivel", draftedBy: null },
    { id: 69, name: "Vitor Roque", club: "PAL", position: "ATA", cost: 0, projPoints: 87.2, realPoints: 0, jogos: 16, gols: 6, assistencias: 1, status: "disponivel", draftedBy: null },
    { id: 70, name: "Yuri Alberto", club: "COR", position: "ATA", cost: 0, projPoints: 73.0, realPoints: 0, jogos: 16, gols: 5, assistencias: 2, status: "disponivel", draftedBy: null },
    { id: 71, name: "Kaio Jorge", club: "CRU", position: "ATA", cost: 0, projPoints: 70.7, realPoints: 0, jogos: 17, gols: 5, assistencias: 2, status: "disponivel", draftedBy: null },
    { id: 72, name: "Savarino", club: "FLU", position: "ATA", cost: 0, projPoints: 80.0, realPoints: 0, jogos: 16, gols: 4, assistencias: 3, status: "disponivel", draftedBy: null },
    { id: 73, name: "Rony", club: "FLU", position: "ATA", cost: 0, projPoints: 68.4, realPoints: 0, jogos: 17, gols: 5, assistencias: 1, status: "disponivel", draftedBy: null },
    { id: 74, name: "Luiz Henrique", club: "BOT", position: "ATA", cost: 0, projPoints: 78.7, realPoints: 0, jogos: 15, gols: 4, assistencias: 3, status: "disponivel", draftedBy: null },
    { id: 75, name: "Calleri", club: "SPFC", position: "ATA", cost: 0, projPoints: 58.5, realPoints: 0, jogos: 16, gols: 4, assistencias: 1, status: "disponivel", draftedBy: null },
    { id: 76, name: "Vegetti", club: "VAS", position: "ATA", cost: 0, projPoints: 65.1, realPoints: 0, jogos: 14, gols: 4, assistencias: 1, status: "disponivel", draftedBy: null },
    { id: 77, name: "Borré", club: "INT", position: "ATA", cost: 0, projPoints: 54.8, realPoints: 0, jogos: 16, gols: 3, assistencias: 2, status: "disponivel", draftedBy: null },
    { id: 78, name: "Claudinho BRA", club: "BRA", position: "ATA", cost: 0, projPoints: 58.6, realPoints: 0, jogos: 17, gols: 3, assistencias: 3, status: "disponivel", draftedBy: null },
    { id: 79, name: "Rayan", club: "VAS", position: "ATA", cost: 0, projPoints: 66.8, realPoints: 0, jogos: 16, gols: 4, assistencias: 2, status: "disponivel", draftedBy: null },
    { id: 80, name: "Memphis Depay", club: "COR", position: "ATA", cost: 0, projPoints: 58.9, realPoints: 0, jogos: 14, gols: 3, assistencias: 2, status: "disponivel", draftedBy: null },
    { id: 81, name: "Neymar SAN", club: "SAN", position: "ATA", cost: 0, projPoints: 67.7, realPoints: 0, jogos: 12, gols: 3, assistencias: 2, status: "disponivel", draftedBy: null },
    { id: 82, name: "Matheus Donelli", club: "COR", position: "GOL", cost: 0, projPoints: 5, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 83, name: "Dalton", club: "VIT", position: "GOL", cost: 0, projPoints: 5, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 84, name: "Vinícius", club: "REM", position: "GOL", cost: 0, projPoints: 5, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 85, name: "Gabriel Vasconcellos", club: "CHE", position: "GOL", cost: 0, projPoints: 5, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 86, name: "Neto", club: "COT", position: "GOL", cost: 0, projPoints: 5, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 87, name: "Alex Muralha", club: "MIR", position: "GOL", cost: 0, projPoints: 5, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 88, name: "Bruno Fuchs", club: "PAL", position: "ZAG", cost: 0, projPoints: 12, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 89, name: "Kannemann", club: "GRE", position: "ZAG", cost: 0, projPoints: 11, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 90, name: "Ignácio", club: "FLU", position: "ZAG", cost: 0, projPoints: 10, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 91, name: "Maicon", club: "VAS", position: "ZAG", cost: 0, projPoints: 10, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 92, name: "Wagner Leonardo", club: "GRE", position: "ZAG", cost: 0, projPoints: 10, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 93, name: "Jemmes", club: "FLU", position: "ZAG", cost: 0, projPoints: 10, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 94, name: "Freytes", club: "FLU", position: "ZAG", cost: 0, projPoints: 10, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 95, name: "Jonathan Jesus", club: "CRU", position: "ZAG", cost: 0, projPoints: 10, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 96, name: "Newton", club: "COT", position: "ZAG", cost: 0, projPoints: 8, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 97, name: "Bastos", club: "COT", position: "ZAG", cost: 0, projPoints: 8, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 98, name: "Camutanga", club: "CHE", position: "ZAG", cost: 0, projPoints: 8, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 99, name: "Romário Bispo", club: "REM", position: "ZAG", cost: 0, projPoints: 7, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 100, name: "Vitor Hugo", club: "CAM", position: "ZAG", cost: 0, projPoints: 10, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 101, name: "Mercado", club: "INT", position: "ZAG", cost: 0, projPoints: 10, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 102, name: "Alex Sandro", club: "FLA", position: "LAT", cost: 0, projPoints: 14, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 103, name: "Jefté", club: "PAL", position: "LAT", cost: 0, projPoints: 14, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 104, name: "Agustín Giay", club: "PAL", position: "LAT", cost: 0, projPoints: 13, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 105, name: "Diogo Barbosa", club: "FLU", position: "LAT", cost: 0, projPoints: 12, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 106, name: "Samuel Xavier", club: "FLU", position: "LAT", cost: 0, projPoints: 12, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 107, name: "Puma Rodríguez", club: "VAS", position: "LAT", cost: 0, projPoints: 12, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 108, name: "Marcos Rocha", club: "GRE", position: "LAT", cost: 0, projPoints: 12, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 109, name: "Bruno Gomes", club: "INT", position: "LAT", cost: 0, projPoints: 11, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 110, name: "Vitinho BOT", club: "BOT", position: "LAT", cost: 0, projPoints: 11, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 111, name: "Caio Paulista", club: "GRE", position: "LAT", cost: 0, projPoints: 11, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 112, name: "Matheuzinho", club: "COR", position: "LAT", cost: 0, projPoints: 11, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 113, name: "Matheus Bidu", club: "COR", position: "LAT", cost: 0, projPoints: 10, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 114, name: "Preciado", club: "CAM", position: "LAT", cost: 0, projPoints: 10, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 115, name: "Arthur Dias", club: "ATH", position: "LAT", cost: 0, projPoints: 10, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 116, name: "Reinaldo", club: "MIR", position: "LAT", cost: 0, projPoints: 10, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 117, name: "Jorginho", club: "FLA", position: "MEI", cost: 0, projPoints: 15, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 118, name: "Pulgar", club: "FLA", position: "MEI", cost: 0, projPoints: 13, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 119, name: "Allan", club: "PAL", position: "MEI", cost: 0, projPoints: 13, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 120, name: "Felipe Anderson", club: "PAL", position: "MEI", cost: 0, projPoints: 13, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 121, name: "Jhon Arias", club: "PAL", position: "MEI", cost: 0, projPoints: 14, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 122, name: "Mauricio", club: "PAL", position: "MEI", cost: 0, projPoints: 14, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 123, name: "Cristian Medina", club: "BOT", position: "MEI", cost: 0, projPoints: 14, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 124, name: "Edenilson", club: "GRE", position: "MEI", cost: 0, projPoints: 13, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 125, name: "Dodi", club: "GRE", position: "MEI", cost: 0, projPoints: 13, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 126, name: "Martinelli", club: "FLU", position: "MEI", cost: 0, projPoints: 14, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 127, name: "Hércules", club: "FLU", position: "MEI", cost: 0, projPoints: 13, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 128, name: "Hugo Moura", club: "VAS", position: "MEI", cost: 0, projPoints: 11, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 129, name: "Marcos Antonio", club: "SPFC", position: "MEI", cost: 0, projPoints: 12, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 130, name: "Charles", club: "COR", position: "MEI", cost: 0, projPoints: 14, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 131, name: "Raniele", club: "COR", position: "MEI", cost: 0, projPoints: 13, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 132, name: "Oscar", club: "SPFC", position: "MEI", cost: 0, projPoints: 13, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 133, name: "Danielzinho", club: "SPFC", position: "MEI", cost: 0, projPoints: 12, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 134, name: "Everton Ribeiro", club: "BAH", position: "MEI", cost: 0, projPoints: 14, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 135, name: "Michel Araújo", club: "BAH", position: "MEI", cost: 0, projPoints: 12, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 136, name: "Acevedo", club: "BAH", position: "MEI", cost: 0, projPoints: 13, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 137, name: "Jadson", club: "ATH", position: "MEI", cost: 0, projPoints: 14, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 138, name: "Bruno Zapelli", club: "ATH", position: "MEI", cost: 0, projPoints: 15, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 139, name: "Alan Patrick INT", club: "INT", position: "MEI", cost: 0, projPoints: 16, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 140, name: "Lucas Silva", club: "CRU", position: "MEI", cost: 0, projPoints: 14, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 141, name: "Neto Moura", club: "MIR", position: "MEI", cost: 0, projPoints: 13, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 142, name: "Alesson", club: "MIR", position: "ATA", cost: 0, projPoints: 16, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 143, name: "André Luís", club: "MIR", position: "ATA", cost: 0, projPoints: 14, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 144, name: "Julimar", club: "ATH", position: "ATA", cost: 0, projPoints: 14, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 145, name: "Willian José", club: "BAH", position: "ATA", cost: 0, projPoints: 14, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 146, name: "Iago", club: "BAH", position: "ATA", cost: 0, projPoints: 13, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 147, name: "Ademir", club: "BRA", position: "ATA", cost: 0, projPoints: 14, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 148, name: "Eduardo Sasha", club: "BRA", position: "ATA", cost: 0, projPoints: 13, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 149, name: "Thiago Borbas", club: "BRA", position: "ATA", cost: 0, projPoints: 12, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 150, name: "André Silva", club: "SPFC", position: "ATA", cost: 0, projPoints: 13, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 151, name: "Bruno Henrique", club: "FLA", position: "ATA", cost: 0, projPoints: 13, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 152, name: "Samuel Lino", club: "FLA", position: "ATA", cost: 0, projPoints: 12, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 153, name: "Ramón Sosa", club: "PAL", position: "ATA", cost: 0, projPoints: 13, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 154, name: "Flaco López", club: "PAL", position: "ATA", cost: 0, projPoints: 12, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 155, name: "Osvaldo", club: "VIT", position: "ATA", cost: 0, projPoints: 13, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 156, name: "Tiquinho Soares", club: "SAN", position: "ATA", cost: 0, projPoints: 14, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
    { id: 157, name: "Wendel Silva", club: "SAN", position: "ATA", cost: 0, projPoints: 11, realPoints: 0, jogos: 0, gols: 0, assistencias: 0, status: "disponivel", draftedBy: null },
];
